### ISSUE TITLE
Better documentation for accounting on Cardano

### ISSUE THREAD

**Issue by alekswithakayy** [IntersectMBO/cardano-db-sync#1095]
Hi everyone,

I'm working on building an analytics dashboard for Cardano and have run into some cases where I can't make sense of how funds are being moved around or how certain values are computed. As an open database, it should be possible to precisely track the movement of and account for every lovelace on the chain.

In an effort to improve transparency, I'd like to write up documentation on confusing accounting events in exchange for understanding how everything works myself.

Here are a few examples of where things don't make sense and I can't (easily) find any resources that explain what's going on:

1. Cumulative Ada from genesis block is 31,112,484,745 Ada while the Cardano website [claims](https://cardano.org/genesis/) 31,112,484,646 Ada was created at genesis (extra is due to 100 ["test ada"](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md#get-tagged-genesis-addresses) - 1,000,000 lovelace that's mysteriously unaccounted for)
2. Genesis outputs [omitted](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md#get-historical-utxo-set-for-a-given-timestamp) after allegra hardfork
3. [Monetary expansion](https://docs.cardano.org/explore-cardano/monetary-policy) is not actually equal to `reserves * 0.003`
4. [Treasury growth](https://docs.cardano.org/explore-cardano/monetary-policy) is equal to `(reserves * 0.003 + fees) * 0.2)` for epochs 209 - 214 but then will be off by several hundred thousand ada for every epoch after
5. Staking rewards are far from being equal to `(reserves * 0.003 + fees) * 0.8)`
6. Rewards are distributed from the reserves at epochs 209, 272, 286, 298 and 299 (pretty sure 209 is some ITN rewards but for the rest I have no idea what the reason is)
7. Fees pot in ada_pots table differs by a few ada from the fees in the epoch table

(This [query](https://github.com/input-output-hk/cardano-db-sync/files/8436315/accounting.txt) illustrates issues 3-7)

I understand that some of these discrepancies are really small and mostly inconsequential. However, it bugs me and I think that a blockchain should just have precise and transparent accounting.

If there are resources that explain any of the examples above, I'd love to see them! Otherwise comments are welcome :)

**Comment by erikd** [comment]
> Genesis outputs [omitted](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md#get-historical-utxo-set-for-a-given-timestamp) after allegra hardfork

This is correct. Any genesis coins that were not redeemed before the Alegra hardfork were returned to the reserves or treasury (I forget which).

**Comment by aleks-djuric** [comment]
Hi Erik, thanks for responding!

> This is correct. Any genesis coins that were not redeemed before the Alegra hardfork were returned to the reserves or treasury (I forget which).

Ok I think it would be valuable if IOG could provide a doc that lists these kind of manipulations to the ledger somewhere and provides some context as to what exactly happened and why. 

> Greater or less than? I suspect its less due to de-registered addresses (explained in response to point 5).

Less, but according to my calculations much less. Like nearly half. I could have missed something but the math is pretty straightforward. Here is my [query](https://github.com/input-output-hk/cardano-db-sync/files/8436315/accounting.txt) and here are the [results](https://docs.google.com/spreadsheets/d/1UQ9G7KF0ZaUOXhkwQgllkWBJx66pyuSKTIxpOJY2EqQ/edit?usp=sharing) from it.

**Comment by JaredCorduan** [comment]
> Ok I think it would be valuable if IOG could provide a doc that lists these kind of manipulations to the ledger somewhere and provides some context as to what exactly happened and why. There are other unexplained manipulations such as 300M ada in reserve rewards occuring in epoch 299.

The reward bug is documented in the `Errata` section of the [Shelley Ledger spec](https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/shelleyLedgerSpec/latest/download-by-type/doc-pdf/ledger-spec) (see Section 17.4).

There were no manipulations of the ledger state at epoch 299. Perhaps what you are seeing is the use of a MIR certificate?

**Comment by jiagengliu** [comment]
> Staking rewards are far from being equal to (reserves * 0.003 + fees) * 0.8)

I believe it shouldn't be this, since `maxPool'` doesn't guarantee that the sum of pools' rewards is equal to this. The [design and incentive document](https://hydra.iohk.io/build/14335804/download/1/delegation_design_spec.pdf) may be helpful.

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
