### ISSUE TITLE
13.0.5 needs resync (atleast from alonzo era)

### ISSUE THREAD

**Issue by rdlrt** [IntersectMBO/cardano-db-sync#1277]
**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.0.5 - linux-x86_64 - ghc-8.10, 8ad98d48e0068f3768d48e18fdcbe254037cba3b
PostgreSQL version: 14.4

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: Hydra pre-compiled binary download

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): systemd

**Additional context**
- As part of fix for #1214 , there was a change introduced for data streamed from node. This only resolves new data coming in, but not old data already synched.
- The release notes only mention need to re-sync if coming from version _prior 13.0.0_.

![image](https://user-images.githubusercontent.com/3169068/194211631-bb846b64-8ba8-49d7-9cd3-44d5beea233f.png)

**Problem Report**

If a user is upgrading from versions 13.0.0-13.0.4 to 13.0.5, they need to resync from genesis (not sure if IO snapshots are correct either).
Depending on steps to be taken, Will be good to update release notes and get a community announcement via Ben to resync from scratch (alternatively, consider bump to a new release as one of the critical data => pool_offline_data was also inaccurate - atleast for 13.0.5 , as reported in #1270 ).

**Comment by kderme** [comment]
We could communicate that in order to fix old values, if someone needs them, a resync is necessary.

Eventually I want to have a form of migration as part of https://github.com/input-output-hk/cardano-db-sync/issues/1172, which goes through old blocks and fixes only the values that are wrong. This means that for each fix like the above, a fix process is also developed. This could be a lot of work, but resyncing from genesis is also quite painful.

> Am I under correct assumption I will have to sync from genesis again if pool_offline_data fix is released

I haven't investigated this issue enough yet.

**Comment by kderme** [comment]
> pool_offline_data fix is released

actually isn't this only used by smash server?

**Comment by erikd** [comment]
No, its populated by the regular `db-sync` executable.

**Comment by mmahut** [comment]
Can someone confirm the IOG snapshots contains the correct values, please?

**Comment by kderme** [comment]
They probably don't, it would require a resync to fix old values. I've built a tool which fixes old values and will be included in the next release. The tool actually indicates that a big number of datum have the wrong bytes 1384311/5764744
```
[db-sync-node:Info:61] [2022-10-13 15:35:30.33 UTC] There are 5764744 Datums. Need to scan them all.
[db-sync-node:Info:61] [2022-10-13 15:35:41.86 UTC] Found some wrong values already. The oldest ones are 
(hash, bytes): [("2512243dcf7a3c3af70e50cdeea19d952e093d2395d95af67d21ed6b92224562","d87a9fd8799f581cd52e11f3e48436dd42dbec6d88c239732e503b8b7a32af58e5f87625413001ffff"),
("f7f2f57c58b5e4872201ab678928b0d63935e82d022d385e1bad5bfe347e89d8","d87980"),
("50707eebc0b23a108309c74e70874daf3c01bc180ecd9d5ee93293b53d456cfa","d87b9fd8799f581cd52e11f3e48436dd42dbec6d88c239732e503b8b7a32af58e5f87625433339391a17d78400ffff"),
("535349dcf2548991b02ea37b4375fc7472ad2f554d061a0e377fcad472e28616","d87a9fd8799f581cd52e11f3e48436dd42dbec6d88c239732e503b8b7a32af58e5f87625443230303001ffff"),
("74bf0fc59a9953a426a1a5f25d952ebc83c03e8fc3c10ce2d49961788388c074","d87a9fd8799f581cd52e11f3e48436dd42dbec6d88c239732e503b8b7a32af58e5f87625443234373901ffff")]
[db-sync-node:Info:61] [2022-10-13 15:41:41.09 UTC] Found 1384311 Datums with mismatch between bytes and hash
[db-sync-node:Info:61] [2022-10-13 15:41:41.09 UTC] Starting chainsync to fix Datums. This will update database values.
```

**Comment by rdlrt** [comment]
Closing as stale
