### ISSUE TITLE
Query by smart contract address...

### ISSUE THREAD

**Issue by mgajda** [IntersectMBO/cardano-db-sync#1288]
**OS**
Linux, but it does not matter.

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):  `12.0.1`
PostgreSQL version: `11.5`

**Build/Install Method**
The method you use to build or install `cardano-db-sync`:
Docker image `inputoutput/cardano-db-sync`

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):
Docker/Kubernetes.

**Additional context**

**Problem Report**

We would like a user-friendly way to search for an address as shown to the user.
Currently querying for `payment_cred` will show a bytestring, instead of `addr...`

Would it be possible to attach a user function to convert bytestring addresses to `addr...` or vice versa?

**Comment by erikd** [comment]
What table are you querying? The only tables with `payment_cred` fields are `tx_out` and `collateral_tx_out`, but both of these tables also have an `address` field which contains the Bech32 address (ie `addr_....`).

**Comment by rdlrt** [comment]
> Would it be possible to attach a user function to convert bytestring addresses to addr... or vice versa?

That'd unnecessarily duplicate entire `hash28type` column for hundreds of millions of outputs, as against the client using `bech32` encoder once on their end (most languages have easy-to-use bech32 library). If anything, might make sense to remove byte or bech-32 encoded `address` field completely , as it is a redundant copy.

> but both of these tables also have an address field

I think he meant the bech32 of `payment_cred` itself (as `address` field would represent base address).

**Comment by kderme** [comment]
Yes I think there is already a lot of duplication in `tx_out`, for example between `address_raw` and `payment_cred` (which I'm not sure if it's really necessary). And that's a very big table to duplicate entries.

**Comment by mgajda** [comment]
Currently the raw addresses are stored by `hash28type` whatever they pertain to.
I would like to query with human-friendly addresses like  `script_hash="addr1wy2mjh76em44qurn5x73nzqrxua7ataasftql0u2h6g88lc3gtgpz"`.

Additionally all `hash28type` entries of different categories are mixed up, which may lead to errors.

**Comment by erikd** [comment]
@mgajda What table are you querying? Providing the actual query would help as well.

**Comment by mgajda** [comment]
> @mgajda What table are you querying? Providing the actual query would help as well.

Working on it, trying to get all redeemer data for a given script address. (This is not an example query, so just checking that it works okay now. Well, it does not, but it will.)

**Comment by erikd** [comment]
@mgajda  The reason I ask is because the `tx_out` table which has the `address_raw` field also has an `address` field which is likely what you are looking for.

**Comment by mgajda** [comment]
I think it would be better if we just have:

1. Separate types (SQL DOMAINs) for different types of addresses, where they are disjoint.
2. FUNCTION to convert between these.
    Adding a text for the `address` increases database size, and is redundant with respect to conversions.
    Am I correct?

**Comment by rdlrt** [comment]
@mgajda - it isnt ideal to be confusing encoding/decoding features with storage in database, it takes no effort to convert strings on client side - [there is an issue](https://github.com/input-output-hk/cardano-db-sync/issues/1333) raised to split out addresses to look up table (similar to stake_address) which might help your cause already, but in general - you shouldnt be relying on Postgres to look for features that increase volume of data (especially for fields like transaction which are expected to go exponentially decrementing performance as well as storage efficiency) - while use of bech32 encode/decode on client side might be a single line with almost no computation.

**Comment by erikd** [comment]
> For now it might be good (if inefficient) workaround,

`db-sync` is already slower than I would like. I would not like to introduce more inefficiencies.

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
