### ISSUE TITLE
tx_out two stake_address_id's for same address

### ISSUE THREAD

**Issue by infnada** [IntersectMBO/cardano-db-sync#1435]
**OS**
Your OS:

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.1.1.2
PostgreSQL version: 15.3

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: inputoutput/cardano-db-sync:13.1.1.2-docker

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**
I'm not sure this is an issue or not but AFAIK an address should be tight to a single stake_address_id. Am i wrong?

Please test the reported query in your end to make sure it's not an issue with my PSQL DB (v15).

Maybe is a rollback problem (as stated in the following lines).

**Problem Report**
A single `address` is reported to have more than one `stake_address_id`. Example:

```
select * from tx_out where address = 'addr1q8e9sjzdhw802nc5ukw95ew8vt2y427vgjhthq7jd2vsu0gx2dylerj6kgx37pp02z89f6tp3g200ju232nnepdffgaqzfn0ja' and stake_address_id IN (5198875, 5198915)
```

|        id       |  tx_id  | index |                                                  address                                                  | stake_address_id |              payment_cred              |
|-----------------|---------|-------|-----------------------------------------------------------------------------------------------------------|------------------|----------------------------------------|
|   142886990     | 53316936|   0   | addr1q8e9sjzdhw802nc5ukw95ew8vt2y427vgjhthq7jd2vsu0gx2dylerj6kgx37pp02z89f6tp3g200ju232nnepdffgaqzfn0ja |     5198915      | 0xF258484DBB8EF54F14E59C5A65C762D44AABCC44AEBB83D26A990E3D |
|   142886994     | 53316936|   4   | addr1q8e9sjzdhw802nc5ukw95ew8vt2y427vgjhthq7jd2vsu0gx2dylerj6kgx37pp02z89f6tp3g200ju232nnepdffgaqzfn0ja |     5198915      | 0xF258484DBB8EF54F14E59C5A65C762D44AABCC44AEBB83D26A990E3D |
|   138834200     | 52041956|   0   | addr1q8e9sjzdhw802nc5ukw95ew8vt2y427vgjhthq7jd2vsu0gx2dylerj6kgx37pp02z89f6tp3g200ju232nnepdffgaqzfn0ja |     5198875      | 0xF258484DBB8EF54F14E59C5A65C762D44AABCC44AEBB83D26A990E3D |

Strange that only one of those stake_addreess_id's exists:

```
select * from stake_address where id IN (5198875, 5198915)
```

|    id   |                  hash_raw                 |                          view                          |            script_hash           |
|---------|------------------------------------------|--------------------------------------------------------|----------------------------------|
| 5198915 | 0xE1065349FC8E5AB20D1F042F508E54E9618A14F7 | stake1uyr9xj0u3edtyrglqsh4prj5a9sc598hew9g4feusk555wszhec3l |                                  |

**Maybe is an issue when rolling back or restarting dbsync in the middle of a transaction insert? If so, i guess your stake_address_id for `stake1uyr9xj0u3edtyrglqsh4prj5a9sc598hew9g4feusk555wszhec3l` will not be the same as mine.**

If it helps to check your DB, the issue came out when trying to create a UNIQUE index on a custom MV which threw an error:

```
CREATE MATERIALIZED VIEW IF NOT EXISTS "mv_payment_address" AS
SELECT
  DISTINCT address,
  digest(address::BYTEA, 'sha256') as sha256,
  encode(address::BYTEA, 'hex') AS "hex",
  stake_address_id AS "stake_address_id",
  tx_out.address_has_script AS "addressHasScript",
  CASE
    WHEN tx_out.address_has_script IS TRUE THEN tx_out.payment_cred
  END AS "scriptHash",
  CASE
    WHEN tx_out.address_has_script IS NOT TRUE THEN tx_out.payment_cred
  END AS "paymentCredential"
FROM tx_out;

-------
CREATE UNIQUE INDEX IF NOT EXISTS unique_sha256 ON mv_payment_address (sha256);
```

My custom MV only have this issue with 2 addresses:

```
SELECT * FROM (
    SELECT
        DISTINCT address,
        COUNT(DISTINCT(stake_address_id)) AS count_stake_address_id
    FROM
        mv_payment_address
    GROUP BY
        address
) as _root
WHERE
    count_stake_address_id > 1
```

|                                                  address                                                  | count_stake_address_id |
|-----------------------------------------------------------------------------------------------------------|-----------------------|
| addr1q8e9sjzdhw802nc5ukw95ew8vt2y427vgjhthq7jd2vsu0gx2dylerj6kgx37pp02z89f6tp3g200ju232nnepdffgaqzfn0ja |           2           |
| addr1qxkcqwk9lkjk8wer9xa6wgk8r30a2jncxwq0ay8tck4eyqsx2dylerj6kgx37pp02z89f6tp3g200ju232nnepdffgaqhykg7g |           2           |

**Comment by infnada** [comment]
It's strange, i don't see any way to delete a row from `stake_address` table, also reflected at https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db-sync/src/Cardano/DbSync/Cache.hs#L233-L234 . So the fact that i don't have an entry for on `stake_address` table for `stake_address_id` = `5198875` could be an inconsistency on my DB caused by a previously PSQL crash with loss of data.

**Comment by kderme** [comment]
Yes this is something that should never happen, since it shows a dangling reference. Could I ask how you synced db-sync? Did you use a snapshot? Upgraded it from a previous version?

**Comment by infnada** [comment]
100% new installation:

```
    image: inputoutput/cardano-db-sync:13.1.1.2-docker
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
      - EXTRA_DB_SYNC_ARGS=--consumed-tx-out
```

If you can't think of any other possible cause of missing entries on `stake_address` i would attribute it to "client side (PSQL)" error and close the issue.

Or maybe its a starting point to create some sort of script to check the consistency of the DB to make sure others "don't face the same luck" or at least they can rely on 100% of the data inside their DBs. If some Wallet, App... use db-sync i would argue to have this "consistency check" scripts would be good to have.

**Comment by kderme** [comment]
Is it possible that some query interfered with normal execution of db-sync? I think it would be hard to do, ie it would require doing some insertions/updates. I wonder if this is somehow related to `--consumed-tx-out` which seems to be enabled.

I agreed on the consistency checks. The easiest way to check is to add a foreign key
`ALTER TABLE "tx_out" ADD CONSTRAINT "tx_out_stake_address_id_fkey" FOREIGN KEY("stake_address_id") REFERENCES "stake_address"("id") ON DELETE CASCADE  ON UPDATE RESTRICT`
which wouldn't work in your case. If it works drop it.

**Comment by infnada** [comment]
I don't think i had anything running interfering with db-sync. Maybe some tests i did refreshing of the custom MV `mv_payment_address` that since i didn't had a UNIQUE index the trigger threw errors, but i don't think it should cause this "loss of data" behavior... 

```
CREATE OR REPLACE FUNCTION mv_payment_address_refresh()
  RETURNS trigger
  LANGUAGE plpgsql
AS $$
  BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_payment_address;
    RETURN NULL;
  END;
$$;

CREATE TRIGGER mv_payment_address_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON tx_out
FOR EACH STATEMENT EXECUTE PROCEDURE mv_payment_address_refresh();
```

Also this (https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db-sync/src/Cardano/DbSync/Era/Shelley/Insert.hs#L313 ) should always insert and/or extract the id of a specific stakeAddress. There should be "no way" to extract an incremental PK Id of a `stake_address` (which exists in the `tx_out` column) and lately not have the data a `stake_address` table. 

Or... maybe there is? https://www.cybertec-postgresql.com/en/gaps-in-sequences-postgresql/ 

I'm thinking of a PSQL Rollback which lead to a gap in the `stake_address` table but db-sync continued using the PK id lately in the insert of `tx_out` row? I don't know much about how db-sync handles this inserts TBH...

------

Regarding consistency checks, i saw these migrations (which seems to be the same you pointed out):
- tx_out fkey -> https://github.com/input-output-hk/cardano-db-sync/blob/master/schema/migration-2-0001-20211003.sql#L28
- collateral_tx_out fkey -> https://github.com/input-output-hk/cardano-db-sync/blob/master/schema/migration-2-0013-20220505.sql#L12

Which maybe a rollback could lead to a delete on `collateral_tx_out` causing a cascade delete on `stake_address` but not on `tx_out`

But since there also exists a DELETE on them on a more recent migration i guess they are old and not in use (affecting in this issue):
- https://github.com/input-output-hk/cardano-db-sync/blob/master/schema/migration-2-0022-20221020.sql#L13
- https://github.com/input-output-hk/cardano-db-sync/blob/master/schema/migration-2-0022-20221020.sql#LL16C106-L16C106

Also checked and those FKeys don't exists on my DB, so this "should not be" what caused the issue. Testing the creation of it lead to expected error:
```
[2023-06-12 13:49:43] [23503] ERROR: insert or update on table "tx_out" violates foreign key constraint "tx_out_stake_address_id_fkey"
[2023-06-12 13:49:43] Detail: Key (stake_address_id)=(5198875) is not present in table "stake_address".
```

So i'm guessing periodically create and delete those FKeys should be enough for consistency checks.

-----

Also regarding `--consumed-tx-out` i didn't check too much how it is implemented and if this could be the cause

**Comment by infnada** [comment]
Tested to force rollbacks on `stake_address` and `tx_out` AFTER INSERT and i saw gaps in PK id but no data inconsistency. Did not test further with possible `Cardano.DbSync.Cache` errors and rollbacks as also don't exactly know how this cache is implemented. I'm out of ideas. Also i don't save full logs of Docker to check what really happened.

Example:
```
CREATE OR REPLACE FUNCTION trigger_function()
RETURNS TRIGGER AS $$
BEGIN

  -- 5678840 current max synced stake_address_id
  if (NEW.stake_address_id IS NULL OR NEW.stake_address_id < 5678840) THEN RETURN NEW; END IF;

  RAISE WARNING 'Inserted row id: % %', NEW.id, NEW.stake_address_id;
  RAISE EXCEPTION 'Forced rollback requested after INSERT';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_insert_trigger
AFTER INSERT ON tx_out
FOR EACH ROW
EXECUTE FUNCTION trigger_function();
```

**Comment by Cmdv** [comment]
Based on the provided information, it seems that the issue has been addressed. We're closing this issue now. If you have any more concerns or if the problem reappears, please let us know by reopening this issue. We appreciate your help!
