### ISSUE TITLE
Get offchain Voting Anchor

### ISSUE THREAD

**Issue by kderme** [IntersectMBO/cardano-db-sync#1527]
This is similar to the off chain pool metadata that we already have.
A new thread needs to be added. The db schema is already in place, but may need adjustments.

**Comment by Cmdv** [comment]
Just a couple of questions for clarification:

1. is there an example of an existing thread that check  "on-chain" with "off-chain" I could use as an example?
2. "read entries from the anchor" is this the anchors on the database if so which one?
3. "do http requests to get the off-chain parts." what url would I use is this getting it from `node` or somewhere else?

**Comment by Cmdv** [comment]
1. 👍 
2. do you have a name/link for the function for the "pool metadata thread"
3. So we're getting N `VotingAnchor`s from db using the url in each to check the SHAs match with what is on the DB, then if valid put into `AnchorOfflineData` and if not then `AnchorOfflineFetchError`?

A new question: Once the `VotingAnchor` is checked/validate, do we "delete" the original or "store" somewhere the last `VotingAnchor` that was checked/validated so we know where to pick up from the next time the thread runs?

**Comment by kderme** [comment]
The thread name is `runOfflineFetchThread`. I suggest you take a look at how it works and it may reply your questions.

**Comment by kderme** [comment]
Note: metadata should be populated only when `--disable-gov` is not on.
