### ISSUE TITLE
Move Instant Rewards to a separate tables

### ISSUE THREAD

**Issue by kderme** [IntersectMBO/cardano-db-sync#1582]
Before implementing this we expect to get some feedback about whether it will be a disruptive change to downstream components. It will be handled by a migration function, so resyncing won't be necessary.

Instant rewards will be completely dropped with Conway. DBSync stores them in the `reward` table with the other staking rewards. Contrary to the staking rewards, IR don't have an associated pool, so `reward.poolId` remains null. This is quite unfortunate, because poolId is part of the unique key of `reward`, so it forces us to have a nullable unique key, which is usually a bad idea.

This has caused a regression on master when syncing mainnet. The reason is that we rely on this unique key to avoid double insertions of stake pool rewards in case of a rollback. There are other solutions to this, but it can be avoided with spliting the tables.

We want to create a separate table eg `instant_reward`. We also want a migration function that will move all entries of `reward` that have a nullable poolId. Finally a new entry in the `extra_migrations` table. All insertions and deletions need to hapen in the same Serializable postgres migration. Future execution of db-sync will avoid the migrations if the `extra_migrations` field exists.

 Note that instant rewards are different from `treasury` or `reserve` certificates, the former is the result, while the latter is the reason.

**Comment by rdlrt** [comment]
As a consumer for this component , my opinion:
- There is opportunity to bump a major version (hasnt happened in a very very long time) when protocol is going through such major revamp, I find it very inefficient to have more complicated configurations while trying to keep it compatible with what was created for old era
- at this point, majority of other components are going through breaking changes anyways
- There are some nice options that have been added, but probabilities of different scenarios to test and consider makes my confidence in testing a setting that will not cause trouble in future is really low.

Specifically about MIR, it would be very basic SQL query adaptation, having to change a small query isnt that big of an impact

**Comment by kderme** [comment]
Note that we have changes in the schema, without forcing users to resync from genesis. For example
- HF changes usually add new functionality, so new tables and fields. Adding new elements doesn't change the existing history so no resynging is necessary.
- Changes like the one proposed here can be implementing by avoiding resyncing, by running a migration procedure, as described above.
- Removing tx_in table is already done, when any of the tx_out flags are used consumed/prune/bootstrap. We don't try to achieve backwards compatibility for these flags anyway.
- Even redundant bech32 fields can be removed as part of a migration (possibly something we want to do)

These changes still affect users and require integration, but they respect the current storage when upgrading db-sync. I think not forcing resyncs in the default schema is quite valuable for many users. The non-vanilla options give other users more flexibility.

We want to organise options by introducing a config file and give config examples https://github.com/IntersectMBO/cardano-db-sync/issues/1576. This is expected to improve the UI, however even when they are organised, the challenge of testing these options still exists.
