### ISSUE TITLE
cardano-db-tool missing from docker image

### ISSUE THREAD

**Issue by nazrhom** [IntersectMBO/cardano-db-sync#1587]
**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.1.0.2
PostgreSQL version:

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: docker

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): docker

**Problem Report**
Please do not include screenshots or images, but instead cut and paste any relevant log messages
or errors. 

Currently `cardano-db-tool` is not included in the provided docker image for db-sync. Having it available in the image would make it easier to generate the snapshots when running db-sync through docker.
I saw a similar feature was requested in https://github.com/IntersectMBO/cardano-db-sync/issues/691 but the PR that closes the issue only implements snapshot restoration support.

**Comment by sgillespie** [comment]
Thanks for the report, I'll add it to the image

**Comment by nazrhom** [comment]
Thank you @sgillespie really appreciate the quick response
