### ISSUE TITLE
 Can't start cardano-db-sync

### ISSUE THREAD

**Issue by zhy827827** [IntersectMBO/cardano-db-sync#1594]
Versions
The db-sync version (eg cardano-db-sync --version): 13.1.1.3
PostgreSQL version: 11.22

Build/Install Method
The method you use to build or install cardano-db-sync: docker-compose

ERROR logs:

```
Connecting to network specified in configuration.yaml
cardano-db-sync: FatalError {fatalErrorMessage = "Error parsing node config: AesonException \"Error in $: key \\\"ApplicationName\\\" not found\""}
Connecting to network specified in configuration.yaml
cardano-db-sync: FatalError {fatalErrorMessage = "Error parsing node config: AesonException \"Error in $: key \\\"ApplicationName\\\" not found\""}
```

docker compose file:

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-13.1.1.3}
    command: [
      "--config", "/config/cardano-db-sync/config.json",
      "--socket-path", "/node-ipc/node.socket"
    ]
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
    depends_on:
      - cardano-node-ogmios
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./config/network/${NETWORK:-mainnet}:/config
      - /opt/cardano-graphql/db-sync-data:/var/lib/cexplorer
      - /opt/cardano-graphql/node-ipc:/node-ipc
    restart: on-failure
    stop_signal: SIGINT
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

**Comment by sgillespie** [comment]
It looks like your cardano-node configuration file is newer than is supported by 13.1.1.3. Where did you get it?

**Comment by zhy827827** [comment]
hello @sgillespie 

I got conifg file from this addr 
 https://github.com/input-output-hk/cardano-configurations/tree/36a75a920de312519c3a9086061daccb997f9cd0

**Comment by rdlrt** [comment]
Why not use default that's part of image itself?

**Comment by zhy827827** [comment]
I did this just to upgrade the version. There were many issues with previous versions, such as querying data

**Comment by sgillespie** [comment]
Try this one: https://github.com/input-output-hk/cardano-configurations/blob/bd40a1ee99782196a70e8fa084a572c276d1d297/network/mainnet/cardano-node/config.json
