### ISSUE TITLE
Offchain Governance Metadata

### ISSUE THREAD

**Issue by Cmdv** [IntersectMBO/cardano-db-sync#1617]
Currently we are storing the whole of the `json` into the Database inside of `OffChainVoteDataJson` / `offchainvote` table
which happens around here:
https://github.com/IntersectMBO/cardano-db-sync/blob/c5d6b8a1da25fbc7f283a34b07ed75dc747131c6/cardano-db-sync/src/Cardano/DbSync/OffChain.hs#L115-L118

current functionality was introduced in [this PR](https://github.com/IntersectMBO/cardano-db-sync/pull/1562)

TLDR currently we:
1. fetch offchain metadata
2. put it into DB inside `OffChainVoteDataJson`

What we'd ideally like is:
1. fech offchain metadata
2. parse metadata
3. put parsed metadata into a new table with same structure as the parsed type
4. link newly created row id in `OffChainVoteDataJson` which is currently of the type`Text`

We can get the expected structure from https://github.com/cardano-foundation/CIPs/pull/632 once it is merged and finalised.

**Comment by kderme** [comment]
An initial implementation of this is done at sancho-4-1-0
