### ISSUE TITLE
sancho-4.1.0 release notes mention compatibility with node-8.9.0

### ISSUE THREAD

**Issue by rdlrt** [IntersectMBO/cardano-db-sync#1665]
The Release notes for [dbsync-sancho-4.1.0](https://github.com/IntersectMBO/cardano-db-sync/releases/tag/sancho-4.1.0) mentions compatibility with cardano-node 8.8.0-pre and probably 8.9.0, but the conway genesis file formats are different between the two. It would be nice if dbsync did not follow node to validate genesis files beyond shelley again (as the pre-fork breaking changes on node unnecessarily complicate downstream components forcing them to make a release).

At the moment, as per my understanding - we do not have a compatible release with node 8.9.x , while IO comms team are [asking infra providers](https://t.me/SPOannouncements/321) to upgrade their infrastructure. For now, the ask of this issue is simply to remove the `probably 8.9.0` from release notes for sancho-4.1.0

**Comment by kderme** [comment]
Thank you I've fixed the release description. An argument to be made is that the genesis file should not change that frequently and should instead be much more stable.

**Comment by kderme** [comment]
Actually db-sync doesn't use the node to validate genesis. In principle it's possible to provide a node-config to db-sync 13.2.0.1 without a `ConwayGenesisFile`. By doing so db-sync assumes some defaults values, which don't really matter when there is no HF to Conway. Of course this won't work for networks that HF to Conway, like sanchonet.

This of course means that node and db-sync use a different node config. However I think it's a good workaround which gives db-sync forward compatibility with node.

**Comment by rdlrt** [comment]
Ye - there are few workarounds/hacks :
1. we can add both version of keys to genesis (atleast pre-fork - where conway genesis is unused).
2. As you mentioned, use a seperate node config that does not have ConwayGenesisFile attribute.
Both the alternatives break automations built based off supposedly established devops process followed by IO teams, and will require exception handling for this specific release - and we dont know how it behaves next week with 8.10.x 🙂

**Comment by rdlrt** [comment]
This is now resolved (release notes updated, as well as `EnableFutureGenesis` flag added)
