### ISSUE TITLE
Ignore Conway Genesis, except in SanchoNet

### ISSUE THREAD

**Issue by sgillespie** [IntersectMBO/cardano-db-sync#1674]
The Conway genesis file frequently changes in backwards-incompatible ways, causing errors like this:
```
cardano-db-sync: Error SNErrConwayConfig: Failed reading Conway genesis file "/configs/conway-genesis.json": "There was an error parsing the genesis file: /configs/conway-genesis.json Error: Error in $.poolVotingThresholds: parsing Cardano.Ledger.Conway.Core.PoolVotingThresholds(PoolVotingThresholds) failed, key \"pvtMotionNoConfidence\" not found"
```

There's no need to load the Conway genesis, unless we're in a network that's in Conway (currently only Sancho). For this reason, we should create a config parameter in the db-sync config, say `"EnableConway"`, defaulting to `false`. This way, we'll only attempt to load the Conway genesis if necessary, which should address this issue for users of Mainnet, Preview, and so on.

**Comment by rdlrt** [comment]
Partly also discussed in #1665 , how will this help in future forks?
1. The config param only applicable on Conway?
2. Will be a stale leftover when we are on Conway across all networks?

Instead - Can this be generalized to something like `EnableFutureGenesis` ?

**Comment by sgillespie** [comment]
> How will this help in future forks?

I don't think it will help directly. 

> Will be a stale leftover when we are on Conway across all networks?

There will be, and we'll need to clean it up as soon as we can.

> Instead - Can this be generalized to something like EnableFutureGenesis ?

This is not a bad idea. @kderme thoughts?

**Comment by kderme** [comment]
`EnableFutureGenesis` seems like a good idea long term.
I believe node config had something similar at some point, but not sure why it was dropped
