### ISSUE TITLE
Incompatibility Issue with PostgreSQL Version (11) in Docker Image and snapshot version (14)

### ISSUE THREAD

**Issue by cshintov** [IntersectMBO/cardano-db-sync#1691]
Tried to restore 13.2 snapshot from https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#13.2/

The dump is for PostgreSQL 14, but the docker image has PostgreSQL 11.21

OS

Ubuntu 20.04

Versions

    cardano-db-sync version: 13.2.0.2
    PostgreSQL version: 14

Build/Install Method

    Docker image from ghcr.io/intersectmbo/cardano-db-sync:13.2.0.2

Run Method

    Docker, command used: docker run -it --entrypoint bash ghcr.io/intersectmbo/cardano-db-sync:13.2.0.2

Additional Context

Attempting to use PostgreSQL version 14 snapshots with the current Docker image, which only includes PostgreSQL version 11.21.

Problem Report

After pulling the latest Docker image for cardano-db-sync (version 13.2.0.2) from the GitHub Container Registry and attempting to verify the PostgreSQL version, it was discovered that the included PostgreSQL version is 11.21. The expectation, based on the operational requirements for using PostgreSQL version 14 snapshots, was that PostgreSQL 14 would be included in the image.

Command Used:

```
docker run -it --entrypoint bash ghcr.io/intersectmbo/cardano-db-sync:13.2.0.2
```

Output Received:

```
bash-5.2# pg_restore --version
pg_restore (PostgreSQL) 11.21
```

**Comment by cshintov** [comment]
That's a different error which was fixed in `13.2.0.2`. Check [merged pr](https://github.com/IntersectMBO/cardano-db-sync/pull/1662/files#diff-af551bc7bddbba216d3cf76b273ad4f10a28c9a56d756b3c605001f7f022bbf6R12)

If you want to work with postgres 14 and sync from snapshot you can use my custom Dockerfile.

```
ARG version="13.2.0.1"

FROM ghcr.io/intersectmbo/cardano-db-sync:${version} as base

# Second stage: Start from a minimal Debian or Alpine base
FROM debian:buster-slim

ARG version
ENV VERSION=${version}
LABEL VERSION=${version}
LABEL BUILD_DATE="2024-05-06"

# Copy everything from the distroless image
COPY --from=base / /

# Install necessary packages for adding repositories
RUN apt-get update && apt-get install -y wget gnupg

# Add PostgreSQL's official repo
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list

# Import the repository signing key
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# Update apt and install PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client-14

STOPSIGNAL SIGINT

ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by cshintov** [comment]
Interesting. I think the `postgresql-setup.sh` needs to use the absolute path in nix store!

something like: `/nix/store/*/bin/sed`

**Comment by sgillespie** [comment]
> Interesting. I think the `postgresql-setup.sh` needs to use the absolute path in nix store!

I don't think this is necessary, we should just be able to add the missing paths here: https://github.com/IntersectMBO/cardano-db-sync/blob/master/nix/nixos/cardano-db-sync-service.nix#L259

**Comment by sgillespie** [comment]
> And it seems this problem is still present in `ghcr.io/intersectmbo/cardano-db-sync:13.2.0.2`

Yes, this is true. We're going to prepare a docker image with this fix in a few days

**Comment by sgillespie** [comment]
How is everyone creating/restoring snapshots from docker? There are a few options I can think of:

 1. The `postgresql-setup.sh` script (has commands like create/restore snapshot)
 2. Environment variable `RESTORE_SNAPSHOT`

If everyone is using (1), it would probably be better to add it to the image (or maybe a new image) along with all its dependencies.

**Comment by cshintov** [comment]
The `postgresql-setup.sh` script is already part of the image. I think it's in `/nix/store`.

And yes I'm setting the `RESTORE_SNAPSHOT` var.

**Comment by Evan-Guan** [comment]
I run using the following command:
```
export NETWORK=mainnet &&\
docker pull cardanofoundation/cardano-graphql-server:8.0.3-${NETWORK} &&\
docker pull cardanofoundation/cardano-graphql-background:8.0.3-${NETWORK} &&\
docker pull cardanofoundation/cardano-graphql-hasura:8.0.3 &&\
docker pull cardanosolutions/cardano-node-ogmios:v6.2.0_8.9.0-${NETWORK} &&\
RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/13.2/db-sync-snapshot-schema-13.2-block-10272678-x86_64.tgz \
docker-compose up -d
```
Still encountering: /nix/store/sipivivjip8mq92inydn2g95d35wn8vs-postgresql-setup.sh: line 194: sed: command not found

**Comment by sgillespie** [comment]
This should be fixed here (as long as you're using postgresql:14): https://github.com/IntersectMBO/cardano-db-sync/pkgs/container/cardano-db-sync/214567424?tag=13.2.0.2-docker
