### ISSUE TITLE
Add epoch_state table

### ISSUE THREAD

**Issue by kderme** [IntersectMBO/cardano-db-sync#1706]
This can include important information per epoch, that remain unchanged for the whole epoch. It can have references to `epoch_params`, `new_committee_info`, `constitution`, enacted proposals, as well as flags like `no_confidence` or `dormant` (this needs to be updated at the end of the epoch).

**Comment by kderme** [comment]
This means that references from `new_committee_info` and `constitution` to `gov_action_proposal` need to become nullable. Rollbacks will have to be adjusted as well.

**Comment by iccicci** [comment]
In a chat @kderme , I understood this could be the right occasion to check #1715 as well.
Thank you
