### ISSUE TITLE
Documentation example misleading

### ISSUE THREAD

**Issue by chrispalaskas** [IntersectMBO/cardano-db-sync#1750]
In doc/running.md at the end we have:
Finally, we can start cardano-db-sync:

PGPASSFILE=config/pgpass-mainnet cardano-db-sync -- \
    --config ~/src/cardano-environments/mainnet/config.json \
    --socket-path ~/src/cardano-environments/mainnet/node.socket \
    --state-dir ~/src/cardano-environments/mainnet/ledger-state \
    --schema-dir schema/

The config file should be db-sync-config.json which we just downloaded from  https://book.world.dev.cardano.org/environments/mainnet/db-sync-config.json and not ~/src/cardano-environments/mainnet/config.json which seems very similar to the cardano-node config from the previous step.
@disassembler

**Comment by Cmdv** [comment]
Good spot, these docs aren't always updated properly it seems. I'll make an amend to rename the config to be correct.

**Comment by Cmdv** [comment]
This was completed by https://github.com/IntersectMBO/cardano-db-sync/pull/1753

**Comment by Cmdv** [comment]
This was completed by https://github.com/IntersectMBO/cardano-db-sync/pull/1753
