### ISSUE TITLE
DB-Sync Incorrectly recording governance protocol parameters

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/cardano-db-sync#1777]
**Network**
- SanchoNet

**Versions**
- Cardano node - 9.0.0
- Db-sync - sancho-5.1.0

**Build/Install Method**
The method you use to build or install `cardano-db-sync`:
- docker image

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):
- docker

**Additional context**

- Related [GovTool issue #1591](https://github.com/IntersectMBO/govtool/issues/1591) with more context.

**Problem Report**

- GovTool queries DBSync current protocol parameter data via the `epoch_param` table and [this query](https://github.com/IntersectMBO/govtool/blob/develop/govtool/backend/sql/get-current-epoch-params.sql#L1).
- Prior to the upgrade to Node 9.0.0 and DBSync sancho-5-1-0, this query would result in the correct current protocol parameters
- Now, some of these parameters are incorrect, it seems like it is governance related parameters which are reported as `0` instead of their correct value.
- For example `"drep_activity": 0, "drep_deposit": 0,` but when these parameters are checked via my local node the results are     `"dRepActivity": 20, "dRepDeposit": 500000000,`.
  - This is further confirmed by the behaviour experienced when trying to register as a DRep via [GovTool issue #1591](https://github.com/IntersectMBO/govtool/issues/1591).

**Comment by kderme** [comment]
Chances are you haven't used ` "EnableFutureGenesis" : true,` in your DBSync config file which 5.1.0 still [requires](https://github.com/IntersectMBO/cardano-db-sync/releases/tag/sancho-5.1.0).
Note that 13.3.0.0 release and future releases will have this true by default.

**Comment by MSzalowski** [comment]
Ok, I've checked and we don't have that flag in our config. We will check it once again after applying this and come back to you as soon as we have more details

**Comment by MSzalowski** [comment]
@kderme We can provide that flag to the binary version of db-sync. But I don't see any option to provide it when we are using docker image to build and install. Does some entry point command that takes config argument like that exist?

**Comment by MSzalowski** [comment]
@kderme Providing config to the binary works as intended, but for the docker image it seems like providing any config takes no effect.  We followed [this docs](https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/docker.md#take-control) of taking control over the db-sync configuration but without success - on the service some default config file was used in execution instead of the one that was passed.

**Comment by kderme** [comment]
With 13.4.0.0 it's now easier to provide the correct config with docker, so this can close.
