### ISSUE TITLE
New off_chain_pool_data record population should be initiated if pool metadata url changes

### ISSUE THREAD

**Issue by hodlonaut** [IntersectMBO/cardano-db-sync#1805]
**OS**
Your OS: Ubuntu

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.3.0.0
PostgreSQL version: 16.2

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: downloaded binaries

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): systemd

**Additional context**

**Problem Report**
Steps to reproduce: 
1. Register a new stake pool, verify that off_chain_pool_data record is created referencing the pool_metadata_ref record referencing metadata url/hash.
2. Wait for half an hour, create a new metadata file with the contents but hosted at a different url e.g. instead of t.json use t2.json.
3. Submit pool update certificate, using new metadata url and valid metadata hash, observe that new pool_metadata_ref record is created okay (expected).
4. Wait for half an hour - check for any references to new pool_metadata_ref id in off_chain_pool_data or off_chain_pool_fetch_error tables... problem: none were found
5. If, subsequently, the content of the file at new location (e.g. t2.json) is edited and new pool update certificate is submitted, the off chain pool data is correctly fetched within next 15 mins of the transaction being stored on the blockchain.

Let me know if you have any questions/need additional information

**Comment by kderme** [comment]
I think it's the `off_chain_pool_data` unique keys that causes this issue, since it doesn't allow same pool and same hash duplications.

**Comment by rdlrt** [comment]
The pool where this started: https://adastat.net/pools/7874e696cf4baca102c098067ca483f2370d2bdc958ad322dadf650b

But upon looking at off_chain_pool_fetch_error, there might be more (maybe just a flavour of behaviour above):

``` sql

select * from pool_metadata_ref where id = 28516;
--   id   | pool_id |                 url                  |                                hash                                | registered_tx_id 
-- -------+---------+--------------------------------------+--------------------------------------------------------------------+------------------
--  28516 |     652 | https://pool.bbhmm.net/poolmeta.json | \x37e5059bbf2798be79328086c34ad0b9940e5511cc3502fcc1d61ffa150f55dd |         49135745
-- (1 row)

select * from off_chain_pool_fetch_error where pool_id = 652 order by id desc limit 1;
--    id   | pool_id |         fetch_time         | pmr_id |                                                         fetch_error                                                         | retry_count 
-- --------+---------+----------------------------+--------+-----------------------------------------------------------------------------------------------------------------------------+-------------
--  675646 |     652 | 2024-08-04 23:44:39.052468 |  28516 | Error Offchain Pool: Timeout error when fetching metadata from PoolUrl "https://pool.bbhmm.net/poolmeta.json": "Connection" |          54

```

The actual connection is fine when using curl from same machine:


``` bash
time curl https://pool.bbhmm.net/poolmeta.json
# {
# "name": "Blockchain Better Have My Money",
# "description": "Delegate to BBHMM - Blockchain Better Have My Money 🔐",
# "ticker": "BBHMM",
# "homepage": "https://www.bbhmm.net/",
# "extended": "https://pool.bbhmm.net/poolmeta_extended.json"
# }
# real    0m0.379s
# user    0m0.028s
# sys     0m0.006s

time ./http-get-json-metadata https://pool.bbhmm.net/poolmeta.json
# http-get-json-metadata: Error Offchain Pool: Timeout error when fetching metadata from https://pool.bbhmm.net/poolmeta.json: "Connection"
# real    0m30.045s
# user    0m0.018s
# sys     0m0.022s
```

@kderme - Happy to move this to it's own post if this seems like a different issue

**Comment by kderme** [comment]
This may be a separate issue, which manifest before the initial issue
