### ISSUE TITLE
epoch_param.gov_action_deposit is not updated

### ISSUE THREAD

**Issue by mirceahasegan** [IntersectMBO/cardano-db-sync#1806]
**OS**
Your OS: Ubuntu

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.3.0.0
PostgreSQL version: unsure

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: Docker image `ghcr.io/intersectmbo/cardano-db-sync:13.3.0.0`

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**

1. Updated Cardano Node image version in `docker-compose.yml` to `image: ghcr.io/intersectmbo/cardano-node:9.1.0`
2. Started on sanchonet: `NETWORK=sanchonet POSTGRES_PORT=5555 docker compose up --build -d`
3. Query `gov_action_deposit`:
```
select epoch_no, gov_action_deposit from public.epoch_param ORDER BY epoch_no DESC LIMIT 1;
epoch_no | gov_action_deposit 
----------+--------------------
   412 |    50000000000
(1 row)
```

- Same issue is observed on Preview too. Wrong `gov_action_deposit`.

**Problem Report**
Returns `50000000000` instead of `100000000000`

**Comment by mirceahasegan** [comment]
On further analysis, the issue is related to how db-sync is started:
- When starting without config file args, and only `NETWORK` env param, the issue reproduces.
- When starting with configuration params, but not passing the `NETWORK` env to the container, the issue does not reproduce.

I am attaching the docker logs for both scenarios, psql output and docker-compose for both scenarios.
1. Log files when issue reproduces:
- [no-config-arg-repro.psql.log](https://github.com/user-attachments/files/16509833/no-config-arg-repro.psql.log)
- [no-config-arg-repro.log](https://github.com/user-attachments/files/16509835/no-config-arg-repro.log)
- [no-config-docker-compose.yml.txt](https://github.com/user-attachments/files/16509854/no-config-docker-compose.yml.txt)

2. Log files when issue does not reproduce:
- [with-config-arg-not-repro.log](https://github.com/user-attachments/files/16509834/with-config-arg-not-repro.log)
- [with-config-arg-not-repro.psql.log](https://github.com/user-attachments/files/16509837/with-config-arg-not-repro.psql.log)
- [with-config-docker-compose.yml.txt](https://github.com/user-attachments/files/16509853/with-config-docker-compose.yml.txt)

**Comment by kderme** [comment]
Release 13.4.0.0 makes it easier to pick the correct config for docker
