### ISSUE TITLE
Transaction Table, Deposit Column doesn't contain drep registration deposit amounts

### ISSUE THREAD

**Issue by johnnuy** [IntersectMBO/cardano-db-sync#1817]
Your OS: Ubuntu 22.04

The `db-sync` version (eg `cardano-db-sync --version`): 13.3.0.0
PostgreSQL version: 14.4
The method you use to build or install `cardano-db-sync`: cabal build process
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): systemd service

I'm looking at migrating my website to use the new dbsync 13.3.0.0 and while evaluating the new tables and columns I've found that the drep_registration deposit amounts are not being rolled up into the tx.deposit value, the same way that stake deposits, and pool deposits are.

I am currently working in the **preview** network as I am no longer running sanchonet nodes.  

Run the following query in the prview dbsync for verification with drep "drep1gkyuayttd2afn2j4xymy4gnz84lq483uxhlluecqhv8gvyj3qcr"

-- Example with DREP deposits Not Rolled Up --
select tx.deposit as "transaction deposit", drep_registration.deposit as "drep deposit", stake_registration.deposit as "stake deposit"
  from drep_hash 
  join drep_registration on drep_registration.drep_hash_id = drep_hash.id
  join tx on drep_registration.tx_id = tx.id
  left join stake_registration on stake_registration.tx_id = tx.id
 where view = 'drep1gkyuayttd2afn2j4xymy4gnz84lq483uxhlluecqhv8gvyj3qcr';

-- Example with Stakepool deposits Rolled Up --
select tx.deposit as "transaction deposit", pool_update.deposit as "pool deposit", stake_registration.deposit as "stake deposit"
  from pool_hash
  join pool_update on pool_update.hash_id = pool_hash.id
  join tx on pool_update.registered_tx_id = tx.id  
  left join stake_registration on stake_registration.tx_id = tx.id
 where pool_update.deposit is not null 
    and pool_hash.view = 'pool1n5aacu3chuvxkm7p2mwcpdvnmkkkvpsje6mclnwj59c6x3wpghh'

In both cases above the stake registration deposit is rolled up as well.

**Comment by kderme** [comment]
I'll try to reproduce. Any chance the drep deregisters at the same tx? This would explain it, since the deposit refunds are subtracted.

**Comment by johnnuy** [comment]
No the deregister is not in the same tx, this is for every drep registration whether it's a registration or a deregistration.

**Comment by kderme** [comment]
Are you sure you're using the correct genesis and that the `epoch_param.drep_deposit` has the expected non-zero values in Conway epochs?

**Comment by johnnuy** [comment]
Looks like the node config was from 9.0.0 without the conway genesis, but it was still running fine... i'm dropping and recreating with the proper node config from 9.1.0

**Comment by johnnuy** [comment]
Issue was missing the conway genesis file in the node config, without dbsync detecting it
