### ISSUE TITLE
pool_stat table data is invalid

### ISSUE THREAD

**Issue by rdlrt** [IntersectMBO/cardano-db-sync#1833]
**OS**
Your OS:

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.4.0.2 (synched from scratch) => 13.4.1.0 (upgrade-in-place) => 13.5.0.0 (upgrade-in-place)

PostgreSQL version: 16.4

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: cabal

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): systemd

**Additional context**

Recently added pool_stat table contains invalid values (atleast for `number_of_blocks` and `number_of_delegators`

**Problem Report**

1. As reported by Smaug on discord, `number_of_delegators` only has 0,1 or 2 as values instead of actual number of delegators to the pool for assigned epoch.
``` sql
select distinct number_of_delegators from pool_stat;
# number_of_delegators
#----------------------
#                    0
#                    1
#                    2
#(3 rows)
```

2. Similarly, `number_of_blocks` seems to lag by 1 epoch => Looks to be expected as per documentation , but not sure if makes sense from data consumption pov
3. For some epochs, the value is invalid (see below):

``` sql
SELECT
  sl.pool_hash_id,
  b.epoch_no,
  ps.number_of_blocks,
  count(b.id) AS correct_number_of_blocks
FROM block AS b
  INNER JOIN slot_leader AS sl ON sl.id = b.slot_leader_id
  LEFT JOIN pool_stat AS ps ON ps.pool_hash_id = sl.pool_hash_id AND ps.epoch_no = b.epoch_no
WHERE sl.pool_hash_id= (SELECT id FROM pool_hash WHERE view = 'pool14wk2m2af7y4gk5uzlsmsunn7d9ppldvcxxa5an9r5ywek8330fg')
GROUP BY sl.pool_hash_id, b.epoch_no, ps.number_of_blocks
ORDER BY sl.pool_hash_id, b.epoch_no LIMIT 10;
# pool_hash_id | epoch_no | number_of_blocks | correct_number_of_blocks 
#--------------+----------+------------------+--------------------------
#          199 |      212 |                0 |                        1   <-- Lags by 1 epoch
#          199 |      213 |                1 |                        2   <-- Lags by 1 epoch
#          199 |      214 |                2 |                        3   <-- Lags by 1 epoch
#          199 |      216 |                0 |                        3   <-- Invalid 0
#          199 |      217 |                3 |                        1   <-- Lags by 1 epoch
#          199 |      218 |                1 |                        1   <-- Lags by 1 epoch
#          199 |      220 |                0 |                        4   <-- Invalid value 0
#          199 |      223 |                0 |                        1   <-- Invalid value 0
#          199 |      225 |                0 |                        4   <-- Invalid value 0
#          199 |      226 |                4 |                        2   <-- Lags by 1 epoch
#          199 |      227 |                2 |                        4   <-- Lags by 1 epoch
```

**Comment by kderme** [comment]
1. is solved https://github.com/IntersectMBO/cardano-db-sync/pull/1874
2. We could use epoch-1, but then the epoch wouldn't match the `epoch_stake` table
3. I  haven't managed to reproduce the issue. The values may not be invalid, but this could be the result of the 1 epoch "lag". When the blocks produced are zero, there is a missing epoch before it eg `epoch_no` jumps from 214 to 216. pool_stat has the correct value, but due to the join it doesn't show.

**Comment by rdlrt** [comment]
Looks promosing, yes your reply to point 3 makes sense indeed.
Look forward to test it out to be sure all cases are resolved, happy to use merged commit to test against guildnet
