### ISSUE TITLE
Increased memory requirements after Chang hardfork

### ISSUE THREAD

**Issue by CodiePP** [IntersectMBO/cardano-db-sync#1836]
**OS**
Your OS: NixOS

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.4.0.1 (really 13.4.0.1 though it reports 13.4.0.0)
PostgreSQL version: 16.4

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: nix build

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): bash script

**Additional context**
The _cardano-db-sync_ process now consumes around 25 GB of RAM. That's around 35% more than 24h ago.

**Problem Report**
Please, investigate and try to lower memory footprint. Is the caching mechanism in place for the new tables?

**Comment by erikd** [comment]
This is likely the `cardano-ledger` issue (apparently no public issue) that triggered a new release of `cardano-node` (https://github.com/IntersectMBO/cardano-node/pull/5967).

**Comment by CodiePP** [comment]
Thank you @erikd  for pointing this out. I recompiled the node on the new version **v9.1.1**, plus db-sync, and everything is back to normal. The cardano-node process takes 15 GB and cardano-db-sync ~14 GB of RAM. That's a great improvement.
