### ISSUE TITLE
Missing metadata for some DREPs

### ISSUE THREAD

**Issue by ironmask285** [IntersectMBO/cardano-db-sync#1859]
**OS**
Your OS:Ubuntu

**Versions**
13.4..0.0
PostgreSQL version: 12

**Problem Report**
Currently, I am noticing missing metadata for some DREPs, for example: drep1wwmwukesapdkwzqycnfmtlva4hxdgmvuudxpczv88ujewk5tgkt. I checked the DREP registration information using the command:
`SELECT dh.view AS "drep_id",
  encode(dh.raw, 'hex') AS "hex",
  dr.*
FROM drep_hash dh
  JOIN drep_registration dr ON (dh.id = dr.drep_hash_id)
WHERE dh.view = 'drep1wwmwukesapdkwzqycnfmtlva4hxdgmvuudxpczv88ujewk5tgkt'`
I see that the voting_anchor_id data is NULL, and the metadata information for this DREP is not synced.

![image](https://github.com/user-attachments/assets/2a641b4b-fc90-4247-aae4-8c4bd35f31e9)

However, when I checked other sources, this DREP does have metadata available. You can check here: https://cardanoscan.io/drep/drep1yfemdmjmxr59kecgqnzd8d0ankkue4rdnn35c8qfsuljt9cjree5m?tab=meta

I have also found that there is quite a bit of similar data. I think there might be an issue during the data synchronization process. Could you help me investigate this problem?

Thank you very much!

**Comment by rdlrt** [comment]
The result of your query:

```sql
SELECT dh.view AS "drep_id", encode(dh.raw, 'hex') AS "hex", dr.* FROM drep_hash dh JOIN drep_registration dr ON (dh.id = dr.drep_hash_id) WHERE dh.view = 'drep1wwmwukesapdkwzqycnfmtlva4hxdgmvuudxpczv88ujewk5tgkt';
                         drep_id                          |                           hex                            | id  |  tx_id   | cert_index |  deposit  | drep_hash_id | voting_anchor_id 
----------------------------------------------------------+----------------------------------------------------------+-----+----------+------------+-----------+--------------+------------------
 drep1wwmwukesapdkwzqycnfmtlva4hxdgmvuudxpczv88ujewk5tgkt | 73b6ee5b30e85b670804c4d3b5fd9dadccd46d9ce34c1c09873f2597 | 306 | 96505205 |          0 | 500000000 |         1664 |                 
 drep1wwmwukesapdkwzqycnfmtlva4hxdgmvuudxpczv88ujewk5tgkt | 73b6ee5b30e85b670804c4d3b5fd9dadccd46d9ce34c1c09873f2597 | 340 | 96587269 |          0 |           |         1664 |              169
 drep1wwmwukesapdkwzqycnfmtlva4hxdgmvuudxpczv88ujewk5tgkt | 73b6ee5b30e85b670804c4d3b5fd9dadccd46d9ce34c1c09873f2597 | 584 | 96898222 |          0 |           |         1664 |              332
 drep1wwmwukesapdkwzqycnfmtlva4hxdgmvuudxpczv88ujewk5tgkt | 73b6ee5b30e85b670804c4d3b5fd9dadccd46d9ce34c1c09873f2597 | 597 | 96930888 |          0 |           |         1664 |              340
(4 rows)

```

**Comment by ironmask285** [comment]
yah,I have got it . Thanks for support
