### ISSUE TITLE
Db-sync snapshot for the preprod network

### ISSUE THREAD

**Issue by Kartiiyer12** [IntersectMBO/cardano-db-sync#1862]
This is essentially needed for testing the db-sync snapshots works properly with the new versions of the db-sync and avoid any issues during the mainnet upgrades during hardforks.

**Comment by sgillespie** [comment]
This is not currently offered by IOG, but there's nothing to stop anyone else from creating and distributing snapshots

**Comment by Cmdv** [comment]
Going to close as it's not something we can offer
