### ISSUE TITLE
Add more useful queries in documentation

### ISSUE THREAD

**Issue by khwerhahn** [IntersectMBO/cardano-db-sync#1863]
**Problem Report**
To understand db-sync better and get devs working faster it would be great to increase the amount of 'useful queries'. Maybe taking TapTools as a good base. It would really help to understand the relationships better. 

1. Current holdings of any address and stakekey
2. Past holdings of any address and stakekey
3. Get asset details (names, logos, etc)

Maybe also some advanced stuff. I don't know if they are possible just from db-sync?
1. Calculate prices for assets (maybe start with Minswap as an example?)
2. A query selecting only "NFTs"
3. Unique wallets trading
4. Trading volume

I'm sure there are many more useful ones.

**Comment by Cmdv** [comment]
This would have to be community driven because as a provider we don't get transparency as to how db-sync is used in the wild and what is "popular". I'll reach out on our Discord channel see if we can get anything there.
