### ISSUE TITLE
Pool_stat is empty, even though pool_stat sync configuration is enabled

### ISSUE THREAD

**Issue by ironmask285** [IntersectMBO/cardano-db-sync#1880]
**OS**
Your OS: Ubuntu 22.04 

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.5.0.2
PostgreSQL version: 12

**Problem Report**
I'm using 13.5.0.2 version to sync onchain-data, and pool_stat sync configuration is enabled (please check my config)
` "insert_options": {
    "tx_cbor": "enable",
    "tx_out": {
      "value": "enable"
    },
    "ledger": "enable",
    "shelley": {
      "enable": true
    },
    "multi_asset": {
      "enable": true
    },
    "metadata": {
      "enable": true
    },
    "plutus": {
      "enable": true
    },
    "governance": "enable",
    "offchain_pool_data": "enable",
    "pool_stat": "enable",
    "json_type": "text"
  },
`

But pool_stat table is empty. Please help me

**Comment by kderme** [comment]
There is an issue in last release, where you need to provide pool_stat**s** instead of pool_stat. This will be fixed for the coming release pre-release https://github.com/IntersectMBO/cardano-db-sync/pull/1878
