### ISSUE TITLE
DB-Sync error reported when running for first time

### ISSUE THREAD

**Issue by mcvetyty** [IntersectMBO/cardano-db-sync#1918]
**OS**
Your OS: Ubuntu 20.x

**Versions**
13.6.0.2
PostgreSQL version: 17

**Build/Install Method**
Guild Operator binary download

**Run method**
Command line

**Additional context**

**Problem Report**
I have completed the install for everything however when I attempt to run ./dbsync.sh at the command line I receive this error:

cardano-db-sync: DBExtraMigration : runExtraMigrations: The use of the config 'tx_out.use_address_table' can only be caried out on a non populated database.

**Comment by mcvetyty** [comment]
Nevermind.. I see what's happening now.

**Comment by keishyo** [comment]
> Nevermind.. I see what's happening now.

Hello @mcvetyty , I'm using CNTools and I have the same issue when run ./dbsync.sh
How do u solve this issue? Thank you

**Comment by mcvetyty** [comment]
> > Nevermind.. I see what's happening now.
> 
> Hello [@mcvetyty](https://github.com/mcvetyty) , I'm using CNTools and I have the same issue when run ./dbsync.sh How do u solve this issue? Thank you

You need to make sure the database snapshot you are using matches the config file you have or else it will take ages to go through and migrate the differences. For me it was a matter of using this snapshot: https://share.koios.rest/share/xFdZDfM4/dbsync/ when using the guild installed config.
