### ISSUE TITLE
Docs Out of Date

### ISSUE THREAD

**Issue by paradoxicalsphere** [IntersectMBO/cardano-db-sync#1919]
**OS**
Ubuntu 22.04.5

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.6.0.4
PostgreSQL version: 15.5

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: Installing from Source (without Nix)

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): N/A

**Additional context**
Following the instructions at https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/installing.md after typing `cabal build all` the following error message displays:

After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-api, ouroboros-consensus,
ouroboros-consensus-diffusion, small-steps, cardano-ledger-shelley,
cardano-chain-gen, ouroboros-network, text, plutus-ledger-api,
ouroboros-consensus-cardano, typed-protocols, plutus-core, io-classes,
ouroboros-network-protocols, ouroboros-network-api,
ouroboros-network-framework, ouroboros-consensus-byron,
cardano-protocol-tpraos, cardano-ledger-alonzo, base,
cardano-ledger-shelley-test, cardano-db-tool, cardano-binary,
ouroboros-consensus-protocol, megaparsec, small-steps-test, text-icu,
cardano-ledger-binary, cardano-ledger-core, cardano-ledger-alonzo-test, aeson,
these, stm, nothunks, exceptions, io-sim, semialign, strict-checked-vars

**Problem Report**
What critical information is missing from the documentation?

**Comment by sgillespie** [comment]
It looks like you need to run `cabal update`. Can you post the full output of `cabal build all`?

**Comment by paradoxicalsphere** [comment]
Thanks for your help:

-----

xx@yy:~/Downloads/cardano-db-sync$ git checkout tags/13.6.0.4
Note: switching to 'tags/13.6.0.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0b7c281a Merge pull request #1910 from IntersectMBO/kderme/13.6.0.4

-----

xx@yy:~/Downloads/cardano-db-sync$ cabal update
Cloning into '/home/pnode/Downloads/cardano-src/cardano-db-sync/dist-newstyle/src/cardano-n_-76eff2ee0c4853a8'...
remote: Enumerating objects: 127938, done.
remote: Counting objects: 100% (3783/3783), done.
remote: Compressing objects: 100% (1421/1421), done.
remote: Total 127938 (delta 2571), reused 3249 (delta 2187), pack-reused 124155 (from 1)
Receiving objects: 100% (127938/127938), 106.87 MiB | 7.93 MiB/s, done.
Resolving deltas: 100% (83855/83855), done.
HEAD is now at 36871ba0c Merge pull request #6043 from IntersectMBO/mwojtowicz/10.1.3
Downloading the latest package lists from:
- hackage.haskell.org
- cardano-haskell-packages
Package list of cardano-haskell-packages is up to date.
The index-state is set to 2024-12-05T13:51:16Z.
Package list of hackage.haskell.org has been updated.
The index-state is set to 2024-12-10T00:56:15Z.
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2024-12-07T08:12:02Z'

-----

xx@yy:~/Downloads/cardano-db-sync$ cabal build all
HEAD is now at 36871ba0c Merge pull request #6043 from IntersectMBO/mwojtowicz/10.1.3
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: cardano-chain-gen-13.6.0.4 (user goal)
[__1] trying: typed-protocols-0.3.0.0 (dependency of cardano-chain-gen)
[__2] next goal: io-classes (dependency of typed-protocols)
[__2] rejecting: io-classes-1.7.0.0 (conflict: typed-protocols =>
io-classes>=1.0 && <1.6)
[__2] skipping: io-classes-1.6.0.0 (has the same characteristics that caused
the previous version to fail: excluded by constraint '>=1.0 && <1.6' from
'typed-protocols')
[__2] trying: io-classes-1.5.0.0
[__3] next goal: stm (dependency of io-classes)
[__3] rejecting: stm-2.5.0.1/installed-2.5.0.1 (constraint from project config
/home/pnode/Downloads/cardano-src/cardano-db-sync/cabal.project requires
>=2.5.3.1)
[__3] trying: stm-2.5.3.1
[__4] trying: text-1.2.4.1/installed-1.2.4.1 (dependency of cardano-chain-gen)
[__5] trying: plutus-ledger-api-1.36.0.0 (dependency of cardano-chain-gen)
[__6] trying: plutus-core-1.36.0.0 (dependency of cardano-chain-gen)
[__7] next goal: megaparsec (dependency of plutus-core)
[__7] rejecting: megaparsec-9.6.1, megaparsec-9.6.0, megaparsec-9.5.0
(conflict: text => base==4.14.3.0/installed-4.14.3.0, megaparsec => base>=4.15
&& <5)
[__7] rejecting: megaparsec-9.4.1, megaparsec-9.3.1, megaparsec-9.3.0,
megaparsec-9.2.2 (conflict: text => base==4.14.3.0/installed-4.14.3.0,
megaparsec => base>=4.15 && <5.0)
[__7] trying: megaparsec-9.2.1
[__8] next goal: exceptions (dependency of plutus-core)
[__8] rejecting: exceptions-0.10.4/installed-0.10.4 (conflict: stm==2.5.3.1,
exceptions => stm==2.5.0.1/installed-2.5.0.1)
[__8] trying: exceptions-0.10.8
[__9] trying: ouroboros-network-protocols-0.12.0.0 (dependency of
cardano-chain-gen)
[_10] next goal: io-sim (dependency of ouroboros-network-protocols)
[_10] rejecting: io-sim-1.6.0.0 (conflict: io-classes==1.5.0.0, io-sim =>
io-classes^>=1.6 || ^>=1.7)
[_10] trying: io-sim-1.5.0.0
[_11] trying: ouroboros-network-framework-0.14.0.0 (dependency of
cardano-chain-gen)
[_12] trying: ouroboros-network-api-0.11.0.0 (dependency of cardano-chain-gen)
[_13] trying: ouroboros-network-0.18.0.0 (dependency of cardano-chain-gen)
[_14] trying: strict-checked-vars-0.2.0.0 (dependency of ouroboros-network)
[_15] trying: ouroboros-consensus-protocol-0.9.0.2 (dependency of
cardano-chain-gen)
[_16] trying: cardano-ledger-shelley-test-1.5.0.0 (dependency of
ouroboros-consensus-protocol)
[_17] trying: small-steps-1.1.0.1 (dependency of cardano-ledger-shelley-test)
[_18] trying: cardano-protocol-tpraos-1.2.0.1 (dependency of
ouroboros-consensus-protocol)
[_19] next goal: ouroboros-consensus-diffusion (dependency of
cardano-chain-gen)
[_19] rejecting: ouroboros-consensus-diffusion-0.18.0.0 (conflict:
ouroboros-network==0.18.0.0, ouroboros-consensus-diffusion =>
ouroboros-network^>=0.17.1)
[_19] skipping: ouroboros-consensus-diffusion-0.17.1.0,
ouroboros-consensus-diffusion-0.17.0.1,
ouroboros-consensus-diffusion-0.17.0.0,
ouroboros-consensus-diffusion-0.16.0.0,
ouroboros-consensus-diffusion-0.15.0.0,
ouroboros-consensus-diffusion-0.14.0.0,
ouroboros-consensus-diffusion-0.13.0.0,
ouroboros-consensus-diffusion-0.12.0.0,
ouroboros-consensus-diffusion-0.11.0.1,
ouroboros-consensus-diffusion-0.11.0.0,
ouroboros-consensus-diffusion-0.10.0.0, ouroboros-consensus-diffusion-0.9.0.0,
ouroboros-consensus-diffusion-0.8.0.2, ouroboros-consensus-diffusion-0.8.0.1,
ouroboros-consensus-diffusion-0.8.0.0, ouroboros-consensus-diffusion-0.7.1.1,
ouroboros-consensus-diffusion-0.7.0.0, ouroboros-consensus-diffusion-0.6.1.0,
ouroboros-consensus-diffusion-0.6.0.0, ouroboros-consensus-diffusion-0.5.1.0,
ouroboros-consensus-diffusion-0.5.0.0, ouroboros-consensus-diffusion-0.4.0.0,
ouroboros-consensus-diffusion-0.3.0.0, ouroboros-consensus-diffusion-0.2.1.0,
ouroboros-consensus-diffusion-0.2.0.0 (has the same characteristics that
caused the previous version to fail: excludes 'ouroboros-network' version
0.18.0.0)
[_19] fail (backjumping, conflict set: cardano-chain-gen,
ouroboros-consensus-diffusion, ouroboros-network)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-api, ouroboros-consensus,
ouroboros-consensus-diffusion, small-steps, cardano-ledger-shelley,
cardano-chain-gen, ouroboros-network, text, plutus-ledger-api,
ouroboros-consensus-cardano, typed-protocols, plutus-core, io-classes,
ouroboros-network-protocols, ouroboros-network-api,
ouroboros-network-framework, ouroboros-consensus-byron,
cardano-protocol-tpraos, cardano-ledger-alonzo, base,
cardano-ledger-shelley-test, cardano-db-tool, cardano-binary,
ouroboros-consensus-protocol, megaparsec, small-steps-test, text-icu,
cardano-ledger-binary, cardano-ledger-core, cardano-ledger-alonzo-test, aeson,
these, stm, nothunks, exceptions, io-sim, semialign, strict-checked-vars
Try running with --minimize-conflict-set to improve the error message.

**Comment by rdlrt** [comment]
Are you using ghc 8.10.7? It does not work if using 9.x (see github action for the tag [here](https://github.com/IntersectMBO/cardano-db-sync/actions/runs/12097785877/job/33733540072) )

**Comment by paradoxicalsphere** [comment]
I was using ghc 8.10.7 and cabal 3.8.1.0 However, changing to cabal 3.10.1.0 does not resolve the error.

**Comment by erikd** [comment]
Something seriously wrong here.  Using `ghc-8.10.7` and `cabal 3.12.1.0` (which should not really matter) I can do:
```
cabal update
git checkout 13.6.0.4 -b tag-13.6.0.4
cabal build all
```
Builds without an issue.

I suspect that parts of your cabal store are damaged in some way. My recommendation is to do the following:
```
cabal clean
rm -rf ~/,cabal/store//ghc-8.10.7/
```
and then try again.

**Comment by paradoxicalsphere** [comment]
I followed the steps above. The file system is not full. The error persists.

I am able to reproduce the error using a different computer. Some more details:

- Both computers are running Ubuntu 22.04.5 LTS.
- Both Ubuntu installations are fresh. One of the computers is hosting a stake pool on Preview Testnet (https://preview.cexplorer.io/pool/pool1ja5uhsx8cmda7x6sqyzrggj07qtncx22lxef398u3ayusfex629). The other computer is a Partner Chains Dependencies server for the Midnight Testnet.
- I successfully compiled cardano-node 10.1.2 / cardano-cli 10.1.1.0 on one of the computers, and successfully compiled cardano-node 10.1.3 / cardano-cli 10.1.1.0 on the other computer prior to attempting to compile cardano-db-sync on each computer.
- After failing to compile cardano-db-sync, I successfully switched to using the Midnight Testnet docker containers to set up the Partner Chains Dependencies server, as described at https://docs.midnight.network/validate/run-a-validator/step-2
- I am new to cardano-db-sync
- When Midnight launches on Mainnet in perhaps a few months, I do not want to run docker containers in production, and would prefer to build cardano-db-sync binaries myself rather than using pre-built binaries.

I hope that may help.

**Comment by sgillespie** [comment]
It could be `text-icu`, try running:
```
cabal install --dry-run --lib text-icu-0.8.0.5
```

and see if it complains about missing libraries

**Comment by paradoxicalsphere** [comment]
xx@yy:~/Downloads/cardano-db-sync$ cabal install --dry-run --lib text-icu-0.8.0.5
Resolving dependencies...
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] next goal: text-icu (user goal)
[__0] rejecting: text-icu-0.8.0.5 (conflict: pkg-config package icu-i18n>=62.1, not found in the pkg-config database)
[__0] rejecting: text-icu; 0.8.0.4, 0.8.0.2, 0.8.0.1, 0.8.0, 0.7.1.0, 0.7.0.1, 0.7.0.0, 0.6.3.7, 0.6.3.6, 0.6.3.5, 0.6.3.4, 0.6.3.3, 0.6.3.2, 0.6.3.1, 0.6.3.0, 0.6.2.1, 0.6.0.1, 0.6.0.0, 0.5.0.1, 0.5.0.0, 0.4.0.1, 0.4.0.0, 0.3.0.0, 0.2.0.0, 0.1, 0.8.0.3 (constraint from user target requires ==0.8.0.5)
[__0] fail (backjumping, conflict set: text-icu)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: text-icu

**Comment by paradoxicalsphere** [comment]
Could I please ask another set-up related question before you close the issue?

How is the PostgreSQL database and credentials specified for cardano-db-sync? I don't see that discussed in the following topics:

https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/installing.md https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/building-running.md
https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/running.md

**Comment by sgillespie** [comment]
We use [postgresql password files](https://www.postgresql.org/docs/current/libpq-pgpass.html), specified as an environment variable:

```
export PGPASSFILE=config/pgpass-mainnet
```

It appears in the _Running_ doc above, but has no explanation. You're free to set up this file as you wish, but we do include one in the repository for convenience at `config/pgpass-mainnet`

**Comment by paradoxicalsphere** [comment]
Thank you again for taking time... now it makes sense.
