### ISSUE TITLE
tx_in table has no data

### ISSUE THREAD

**Issue by sharkfin22** [IntersectMBO/cardano-db-sync#1925]
**OS**
Ubuntu 24.04

**Versions**
cardano-db-sync 13.6.0.2 - linux-x86_64 - ghc-8.10
git revision 944e53232ad5f5f87ed97634d2e4e08496db7a1c

PostgreSQL version:
 PostgreSQL 17.1

**Build/Install Method**
Guild tools

**Problem Report**
My db-sync node seems to be synced, but I do not see any data inside the tx_in table. 

Db-sync seems to be taking 591GB+ data in the database, and other tables look like they are populated except for this one.

**Comment by sgillespie** [comment]
Do you have anything extra in `sync_options` in your `db-sync-config.json`?
