### ISSUE TITLE
Please provide the capability to build from source to a statically linked binary. 

### ISSUE THREAD

**Issue by melmccann** [IntersectMBO/cardano-db-sync#270]
I am unable to, using nix-build, build a statically linked binary from the source code. The only way to get these is from the Hydra build. Please add the necessary changes to make this possible.

**Comment by craigem** [comment]
Hi @melmccann :-)

Does either:
```
$ nix build -f . cardano-db-sync
```
or
```
$ nix-build . -A cardano-db-sync
```
do what you require?

**Comment by sevanspowell** [comment]
If you find that isn't what your looking for, shoot me a link to where you're finding the statically-linked binary currently and I should be able to get you the command to reproduce that locally.

**Comment by Mercurial** [comment]
```cabal build all``` also works

**Comment by Cmdv** [comment]
Based on the provided information, it seems that the issue has been addressed. We're closing this issue now. If you have any more concerns or if the problem reappears, please let us know by reopening this issue. We appreciate your help!
