### ISSUE TITLE
Add new validation for Shelley transaction accounting

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-db-sync#274]
Arising from: https://github.com/input-output-hk/cardano-db-sync/issues/272

The validation should chose a random transaction and check that:
```
sum_of_input_values + sum_of_withdrawal_values - tx_fee = sum_of_output_values
```
Obviously for Byron era transactions (and a large portion of Shelley transactions), `sum_of_withdrawal_values` will be zero.

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
