### ISSUE TITLE
More validations

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-db-sync#277]
Could also validate that:

* ~All recorded timestamps are in the past (ie catch https://github.com/input-output-hk/cardano-db-sync/issues/276)~ PR #396 merged.
* ~Block time stamps are monotonically increasing with `slot_no`~ PR #396 merged.
* ~Block numbers are monotonically increasing (and strictly increasing by 1)~. PR #396 merged.
* For a random address, validate UTxO balance from the database matches the UTxO balance from ledger state.
* Other validations that compare database values with ledger state values.
* ~Query to find any transaction where accounting does not add up~. PR #396 merged.
* Accounting of rewards (ie https://github.com/input-output-hk/cardano-db-sync/issues/361, #379).

**Comment by kderme** [comment]
> For a random address, validate UTxO balance from the database matches the UTxO balance from ledger state.

This can be very slow for the ledger state. The outputs are stored in a compact serialised format. So we need to go through all the UTxO values, deserialise them and filter them based on the address.

**Comment by erikd** [comment]
> So we need to go through all the UTxO values, deserialise them

Would it not be possible to convert the target address to the compact form and filter the UTxO set on that?

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
