### ISSUE TITLE
Unhandled DCertGenesis certificate

### ISSUE THREAD

**Issue by disassembler** [IntersectMBO/cardano-db-sync#290]
Error when re-registering geensis delegations:

```
[db-sync-node:Error:35] [2020-09-11 11:06:39.21 UTC] insertCertificate: Unhandled DCertGenesis certificate
```

Recovers fine and ignores it. Maybe this should be WARN instead of error. Although at some point we should update db-sync to support genesis delegation certificates.

**Comment by Cmdv** [comment]
Based on the provided information, it seems that the issue has been addressed. We're closing this issue now. If you have any more concerns or if the problem reappears, please let us know by reopening this issue. We appreciate your help!
