### ISSUE TITLE
db-sync documentation improvements

### ISSUE THREAD

**Issue by dorin100** [IntersectMBO/cardano-db-sync#342]
- the documentation for db-sync does not provide any build instructions for cabal (and we are instructing our users to use cabal for the cardano-node to which db-sync connects to)
- the documentation could be clearer when referring to the different possible environments (mainnet, testnet, staging, qa, etc) - how to connect and build
- it is not clear why a user would use this product/app - like what can you do with it? what you cannot do?
- it would be useful to provide some real examples like: (i) how you can see the rewards received by a specific key in one epoch or (ii) how many blocks were created by a specific pool in one epoch (if it is possible at all), etc

**Comment by dorin100** [comment]
The above comments refer both to the Github repo and https://docs.cardano.org/projects/cardano-db-sync/en/latest/.

**Comment by erikd** [comment]
The docs on docs.cardano.org are from the `Readme.md` tile in the repo.

**Comment by erikd** [comment]
> it would be useful to provide some real examples like: (i) how you can see the rewards received by a specific key in one epoch or (ii) how many blocks were created by a specific pool in one epoch (if it is possible at all), etc

Unfortunately, there are basically an infinite number of example queries I could provide. There are already a number provided a https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md

**Comment by erikd** [comment]
I **never** use `Nix` for `db-sync` and **only** build with `cabal`.

**Comment by Cmdv** [comment]
Based on the provided information, it seems that the issue has been addressed. We're closing this issue now. If you have any more concerns or if the problem reappears, please let us know by reopening this issue. We appreciate your help!
