### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by PegasusPool** [IntersectMBO/cardano-db-sync#515]
Is it possible to include the cardano-db-sync binaries as part of the release (as it's done for cardano-wallet)?

**Comment by erikd** [comment]
I am pretty sure there is already Nix as well as docker recipes for this. Is that not enough?

 How would you propose this is package any binary? `db-sync` is in some ways more difficult to package than the wallet because it has external dependencies (postgresql) as well as having to find somewhere to put the SQL migration files.

**Comment by Fell-x27** [comment]
> Is that not enough?
No. Not every user uses docker and\or nix. Wold be nice if there was choice to download native binaries only.
> because it has external dependencies (postgresql) 
It's not a problem of the project. It's problem of user who didn't read docs. Also nobody asks to publish binaries **instead** docker\nix. Who needs docker - downloads docker. But many people want just clear binaries.

**Comment by dmitrystas** [comment]
Yes, it would be great if we could just download binaries, like for example https://hydra.iohk.io/build/5446647 for a node

**Comment by hodlonaut** [comment]
I echo the above sentiments, archive with binaries would be much appreciated!

**Comment by erikd** [comment]
The `node` binaries are built as statically linked using Nix. Unfortunately this is not possible for `db-sync` because it needs to link to the PostgreSQL C library which is not easily buildable.

**Comment by Fell-x27** [comment]
>Unfortunately this is not possible for db-sync because it needs to link to the PostgreSQL C library which is not easily buildable.

cardano-wallet is built with a whole SQLite onboard, and there is no problem to distribute it as standalone-binary. 
Moreover, there is a [native haskell psql adapter](https://hackage.haskell.org/package/postgresql-simple). It's just a first one i've found. There should be more I'm sure.

**Comment by erikd** [comment]
What the wallet does with SQLIte is irrelevant. `db-sync` uses PostgreSQL, not SQLIte.

Also, we already use `postgres-simple` which dependes in `postgres-libpq` which binds to and requires the C library.

**Comment by Fell-x27** [comment]
So what's problem? Just release binaries. Developer, who needs binaries only, will install psql and all libraries by himself, it's a simple and common case.

We dont ask you to release all files needed to launch db-sync by one command. Just binaries of db-sync. Without psql, without external libs. We can satisfy dependences, don't worry. We will see runtime errors like "cant load library_name, file doesnt exist" and understand wnat it means. It's not a big deal.

Everything we need its just have an ability to switch versions of db-sync by switching the  executable file within our enviroment, but do not build it manually with cabal\ghc\etc headache.

**Comment by erikd** [comment]
> Just release binaries. 

The node and wallet are released as statically linked binaries. Unfortunately we not yet able to **build** a statically linked binary for `db-sync`. So what do we do? Ship a binary that is dynamically linked and works on some systems but not others? Release separate binaries for every Linux variant users may want to run this on?

> We can satisfy dependences, don't worry. We will see runtime errors like "cant load library_name, file doesnt exist" a

Yes, you may be able to solve this, but there are **certain** to be other people who cannot and that then provides a support headache for us.

We are still working on building this thing statically.

**Comment by Fell-x27** [comment]
>Ship a binary that is dynamically linked and works on some systems but not others? 

Yep. And write it in the docs, that there are some dependences. Or do some checks in the runtime and show message to the user right in the console. Like "Dude, you have to install psql and psql-dev in order to use db-sync, mkay?" 

>Release separate binaries for every Linux variant users may want to run this on?

Every linux user can install needed packets manually. DB-sync it's a developers-oriented software, I'm sure they all know how to use a packet manager.

**Comment by wei3hua2** [comment]
Do you guys have problem with long build time?

When I build using local laptop, it took me hours.

I tried with EC2 t4.medium instance and left it overnight, it broke halfway. Still trying to figure out why.

**Comment by erikd** [comment]
@wei3hua2  How are you building it?

**Comment by wei3hua2** [comment]
> @wei3hua2 How are you building it?

I follow the instruction from [Set up and run the db-sync node](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/building-running.md#set-up-and-run-the-db-sync-node
) but skip te final 2 script execution statements. Basically these:

```
git clone https://github.com/input-output-hk/cardano-db-sync
cd cardano-db-sync
nix-build -A cardano-db-sync -o db-sync-node
```

My nix is a fresh installation, following the instruction from [the page](https://nixos.org/download.html)

`curl -L https://nixos.org/nix/install | sh`

**Comment by erikd** [comment]
Do you have the IOHK Nix cache enabled? If you do not, it **will** take a long time.

**Comment by wei3hua2** [comment]
> Do you have the IOHK Nix cache enabled (as described in the first section of the build document)? If you do not, it **will** take a long time.

Oh my god, you saved me.

**Comment by erikd** [comment]
We are in the process of working towards a `9.0.0` release of `db-sync`.

We are also able to build a musl static binary which is available [here](https://hydra.iohk.io/build/5777933). This has not been tested.

**Comment by erikd** [comment]
Is this sufficient to close this?

**Comment by Cmdv** [comment]
Based on the provided information, it seems that the issue has been addressed. We're closing this issue now. If you have any more concerns or if the problem reappears, please let us know by reopening this issue. We appreciate your help!
