### ISSUE TITLE
Account balance example

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-db-sync#559]
I might be a tad late to the party, but would you mind sharing how one would track a balance of an account, for example?

Calculating  `outputs + reward + reserve +  treasury - inputs - withdrawal` won't do the trick and there doesn't seem to be a nice and easy way around this.

A good candidate could be `stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq` (rewards account for an already retired pool). Different explorers show this in a different manner, but I think it's currently not possible without any kind of workaround / additional cumbersome computing. Things become even more blurry when taking edge cases into account. With all that in mind, wouldn't it be beneficial to explicitely track `reap` (in addition to `deposit`) info along with account and epoch in the dbsync?

_Originally posted by @1000101 in https://github.com/input-output-hk/cardano-db-sync/issues/474#issuecomment-804793203_

**Comment by 1000101** [comment]
Thanks for opening this issue on my behalf! Just to clarify a bit more - it's not just about the account per se, but mainly about tracking `reap` somewhere in the db so it could be easily used in computation of account balance (which is used everywhere, e.g. pool live stake size, pool live pledge, etc.).

**Comment by erikd** [comment]
@1000101 What is "reap" ? There is no table or column in db-sync called "reap".

**Comment by erikd** [comment]
Account balance is not trivial.

Addresses in the Shelley and later era have two components; a payment credential and a staking credential. The stake address (eg `stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq`) is derived from the later. However it is possible to construct a valid address which does not contain any staking credential.

So while it would be possible to get the account balance for a particular stake address, there is no way to get the account balance of a wallet unless every address in that wallet includes a staking credential.

**Comment by 1000101** [comment]
> @1000101 What is "reap" ? There is no table or column in db-sync called "reap".

Oh, I'm sorry for not clarifying this enough. What I meant is described in https://github.com/input-output-hk/cardano-db-sync/issues/474. There is currently no way of easily computing balance of an account, when this account has been used in pool registration (as a reward account) and later on the pool was retired, thus regaining the pool deposit. The "payment" of pool deposit is tracked in dbsync, but not its "refunds" when a pool is retired.

**Comment by xdzurman** [comment]
I agree with this. There are also numerous edge cases each "user" of cardano-db-sync would have to handle. Both Adalite and Yoroi are confused when they see an account which was previously a reward account of a retired pool:
![image](https://user-images.githubusercontent.com/22454337/113694204-bf7d7900-96cf-11eb-90fb-d38c951f5c4e.png)
![image](https://user-images.githubusercontent.com/22454337/113694292-d754fd00-96cf-11eb-8558-efd542e284b6.png)

There should be an easy relation which would be updated the same way as rewards are automatically added. Let's take a [pool with multiple deregistrations](https://cardanoscan.io/pool/9c8e59ea7004a51f953642653d70a94d066359b9dd6e6416a5430ff3) as an example, since that is actually pretty common and it's hard to handle the reward balance of its owner account.

There are 9 retirement certificates to it
![image](https://user-images.githubusercontent.com/22454337/113694716-64985180-96d0-11eb-80ca-3ca27d751246.png)

And 15 registration certificates
![image](https://user-images.githubusercontent.com/22454337/113694801-80035c80-96d0-11eb-9d33-9f28b788cb0b.png)

There are numerous edge cases and vague rules of [retirement overruling by new certificaes](https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/retire_stakepool.html). 

@erikd, if you insist on sufficient connection between 500 tx deposit and the retirements, how would you write a query for reward account balance of one of its owner accounts - e127e9e94eaa9287680e877832700a1724255e9688609497e09a6c440f? If not, can we add this **explicitly** to db-sync? Let's say, as a new table, named **pool_deposits**, with **addr_id**, **amount** (currently should be a multiple of 500) and **epoch_no**?

**Comment by erikd** [comment]
Currently `db-sync` extracts data from the ledger state and inserts in in the database. It discards some information, but does not do any aggregations. What is inserted into the database is simply a reflection of what ledger state provides.

Lets look at the relevant `pool_hash.id`:
```sql
> select id, hash_raw from pool_hash
    where hash_raw = '\x9c8e59ea7004a51f953642653d70a94d066359b9dd6e6416a5430ff3' ;
  id  |                          hash_raw                          
------+------------------------------------------------------------
 5022 | \x9c8e59ea7004a51f953642653d70a94d066359b9dd6e6416a5430ff3
(1 row)

```
The pool was registered (extra joins to put them in order of `block_no` ascending) as follows:
```sql
> select pool_update.id, hash_id, cert_index, active_epoch_no, block.block_no from pool_update
    inner join tx on tx.id = pool_update.registered_tx_id
    inner join block on tx.block_id = block.id
    where pool_update.hash_id = 5022
    order by block.block_no asc; 
  id  | hash_id | cert_index | active_epoch_no | block_no 
------+---------+------------+-----------------+----------
 5022 |    5022 |          0 |             220 |  4717004
 5023 |    5022 |          0 |             220 |  4717035
 5024 |    5022 |          0 |             220 |  4717057
 5029 |    5022 |          0 |             220 |  4717140
 5030 |    5022 |          0 |             220 |  4717146
 5031 |    5022 |          0 |             220 |  4717169
 5032 |    5022 |          0 |             220 |  4717189
 5033 |    5022 |          0 |             220 |  4717216
 5034 |    5022 |          0 |             220 |  4717234
 5035 |    5022 |          0 |             220 |  4717241
 5037 |    5022 |          0 |             220 |  4717296
 5038 |    5022 |          0 |             220 |  4717425
 5061 |    5022 |          0 |             220 |  4721000
 5080 |    5022 |          0 |             221 |  4725394
 5081 |    5022 |          0 |             221 |  4725435
(15 rows)
```
and deregistered in:
```sql
> select pool_retire.id, hash_id, cert_index, retiring_epoch, block.block_no from pool_retire
    inner join tx on tx.id = pool_retire.announced_tx_id
    inner join block on tx.block_id = block.id
    where hash_id = 5022
    order by block.block_no asc ; 
 id  | hash_id | cert_index | retiring_epoch | block_no 
-----+---------+------------+----------------+----------
 180 |    5022 |          0 |            219 |  4717395
 181 |    5022 |          0 |            219 |  4717397
 182 |    5022 |          0 |            219 |  4717401
 183 |    5022 |          0 |            219 |  4717403
 184 |    5022 |          0 |            219 |  4717405
 185 |    5022 |          0 |            219 |  4717417
 186 |    5022 |          0 |            219 |  4717430
 187 |    5022 |          0 |            220 |  4725366
 188 |    5022 |          0 |            220 |  4725717
(9 rows)
```
De-intrerleaving updates and deregistrations:
```
register 4717004
update   4717035
update   4717057
update   4717140
update   4717146
update   4717169
update   4717189
update   4717216
update   4717234
update   4717241
update   4717296
retire   4717395
retire   4717397
retire   4717401
retire   4717403
retire   4717405
retire   4717417
update   4717425
retire   4717430
update   4721000
retire   4725366
update   4725394
update   4725435
retire   4725717
```
To be continued ....

**Comment by erikd** [comment]
This is definitaly too much of a pain in the neck. Talking with ledger-specs people to try to come up with a solution.

**Comment by erikd** [comment]
Spoken to the `ledger-specs` people who suggested a quick and dirty way to fudge it for now while waiting for a better solution.

The idea would be to have something like a `pool_registration_refund` table containing the stake address and the amount.

**Comment by xdzurman** [comment]
That'd be great!

**Comment by 1000101** [comment]
> Spoken to the `ledger-specs` people who suggested a quick and dirty way to fudge it for now while waiting for a better solution.
> 
> The idea would be to have something like a `pool_registration_refund` table containing the stake address and the amount.

Awesome! I mean, we do have a workaround in place for now, but it's around 100 lines of not-so-pretty:tm: SQL which has to be computed per every account. This would definitely help a ton. Thanks a mil!!!

**Comment by xdzurman** [comment]
@erikd Hello, can we get an update on this?

**Comment by erikd** [comment]
Sorry, snow under with other stuff like Alonzo support.

**Comment by erikd** [comment]
Given a Shelley era address, getting the related stake address can be done using:
```sql
select stake_address.id as stake_address_id, tx_out.address, stake_address.view as stake_address
    from tx_out inner join stake_address on tx_out.stake_address_id = stake_address.id
    where address = 'addr1qx2kd28nq8ac5pr...08ly3tu9sy0f4qd' ;
 stake_address_id |         address                      |           stake_address
------------------+--------------------------------------+-------------------------------------
                1 | addr1qx2kd28nq8ac5p...8ly3tu9sy0f4qd | stake1u9ylzsgxaa6xct...nljg47zctvm3rc
```
Using the `stake_address_id` (`X` in the following) it is then possible to get:

* The sum of the inputs to an address:
    ```
    select sum (value) from tx_out where stake_address_id = X ;
    ```
* The sum out the outputs and fees:
    ```
    select sum (tx_out.value) as value, sum (tx.fee) as fee
        from tx_out inner join tx on tx_out.tx_id = tx.id
        inner join tx_in on tx_in.tx_out_id = tx.id and tx_in.tx_out_index = tx_out.index
        where tx_out.stake_address_id = X ;
    ```
* The sum of the rewards:
    ```
    select sum (amount) from reward where addr_id = X ;
    ```
 * The sum of the withdrawals:
     ```
     select sum (amount) from withdrawal where addr_id = X ;
     ```

The balance of the address therefore should be: `inputs + rewards - outputs - withdrawals`

However, for a couple of stake addresses I have tried, this does not match the balance displayed in Daedalus.

**Comment by xdzurman** [comment]
I'm sorry but this whole issue is about getting the right balance for accounts which were previously pool owners, then retired their pools, withdrawed the 500 ADA deposit and now their balance is screwed because the "+500 ADA to this stake address" is nowhere in the db

**Comment by erikd** [comment]
@xdzurman I realize that what you are after is more complicated than this, but I need to sort this out in order to figure out your issue. This is a stepping stone and I am documenting where I am up to.

**Comment by xdzurman** [comment]
Alright, thanks, I thought that was the final answer.

**Comment by erikd** [comment]
Working on some code to help me extract data from the database and make sense of it.

**Comment by erikd** [comment]
I now have some code (which will end up in `cardano-db-tool` that can calculate the balance for a given stake address.

That code seems to work correctly for all stake addresses that have not been used for a deposit for a pool registration. Once of the addresses it gives a strange result for is `stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq` for which the current balance is `-496.330611` which is obviously wrong.

Still investigating.

**Comment by erikd** [comment]
The additions to `cardano-db-tool` are in #658 .

**Comment by erikd** [comment]
Trying to find pool de-registration refund which as I understand are returned as a reward in a later epoch. For example, if a pool is de-registered in epoch `N`, the deposit will be refunded at the start of epoch `N + 2`.

So, lets find the `id` of our stake address:
```sql
select id, view from stake_address where view = 'stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq' ;
   id   |                            view                             
--------+-------------------------------------------------------------
 193865 | stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq
(1 row)
```
Are there any rewards for that address?
```sql
select * from reward where addr_id = 193865 ; 
 id | addr_id | type | amount | epoch_no | pool_id 
----+---------+------+--------+----------+---------
(0 rows)
```
What????

**Comment by 1000101** [comment]
> I now have some code (which will end up in `cardano-db-tool`) that can calculate the balance for a given stake address.
> 
> That code seems to work correctly for all stake addresses that have not been used for a deposit for a pool registration. Once of the addresses it gives a strange result for is `stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq` for which the current balance is `-496.330611` which is obviously wrong.
> 
> Still investigating.
> 
> @xdzurman Is your wallet still reporting a balance of `-499.705973` ?

Blockfrost shows 3669389 Lovelaces for this account.
```
curl https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq

{
"active":true,"active_epoch":219,
"controlled_amount":"3669389",
"rewards_sum":"0",
"withdrawals_sum":"500000000",
"reserves_sum":"0",
"treasury_sum":"0",
"withdrawable_amount":"0",
"pool_id":"pool1tz9k09jylmnk74z74v2t384smfypr7cwpzvs5sd2w537wu5jlrk"
}

```
If you'd be interested, I can share an SQL snippet (~100 lines of code) of workaround we currently use to deal with this.

**Comment by 1000101** [comment]
> Trying to find pool de-registration refund which as I understand are returned as a reward in a later epoch. For example, if a pool is de-registered in epoch `N`, the deposit will be refunded at the start of epoch `N + 2`.
> 
> So, lets find the `id` of our stake address:
> 
> ```sql
> select id, view from stake_address where view = 'stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq' ;
>    id   |                            view                             
> --------+-------------------------------------------------------------
>  193865 | stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq
> (1 row)
> ```
> 
> There are no rewards for that address
> 
> ```sql
> select * from reward where addr_id = 193865 ; 
>  id | addr_id | type | amount | epoch_no | pool_id 
> ----+---------+------+--------+----------+---------
> (0 rows)
> ```
> 
> but there is a withdrawal:
> 
> ```
> select * from withdrawal where addr_id = 193865 ; 
>   id   | addr_id |  amount   |  tx_id  
> -------+---------+-----------+---------
>  31269 |  193865 | 500000000 | 2859775
> (1 row)
> ```
> 
> So why is there a withdrawal, but that address has no entries in the `reward` table? As I understood it, withdrawals come from the reward account.

That's the problem. It's nowhere in dbsync. We have to compute it manually. Moreover, I thought the refund happens instantly in the epoch N where pool deregistration takes place (not N+2, as with rewards).

**Comment by erikd** [comment]
@1000101 I am still working on this. That means there is no need to re-tell me what I already know.

**Comment by erikd** [comment]
> Blockfrost shows 3669389 Lovelaces for this account.

Ok, that means we are only missing the refund for the pool deposit. Apparently this is not something that is on-chain but is part of the ledger state. I am currently trying to figure out how to extract it.

**Comment by erikd** [comment]
Have agreement from the `ledger-specs` team that information to populate a `pool_deposit_refund` table is needed, but no idea of when it will arrive.

**Comment by 1000101** [comment]
@erikd this has been resolved in https://github.com/input-output-hk/cardano-db-sync/issues/826 right?

**Comment by Cmdv** [comment]
Based on the provided information, it seems that the issue has been addressed. We're closing this issue now. If you have any more concerns or if the problem reappears, please let us know by reopening this issue. We appreciate your help!
