### ISSUE TITLE
Write a query to calculate the time delta between all adjacent blocks 

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-db-sync#573]
This could be used to generate a histogram.

**Comment by dcoutts** [comment]
This would be used to compare the actual distribution of block times to the expected "perfect" distribution based on theory. The difference between the two can show us our deviation from perfection.

**Comment by erikd** [comment]
For only the Shelley era, the query is pretty trivial:
```
select block_no, time, time - lag (time) over (order by time asc) as delta from block where epoch_no >= 208 ; 
```

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
