### ISSUE TITLE
testnet-config.yaml does not non-existant testnet-config.yaml

### ISSUE THREAD

**Issue by TinFury** [IntersectMBO/cardano-db-sync#591]
Building and running referes to testnet-config.yaml which does not exist. Other config file will not connect to testnet.

PGPASSFILE=config/pgpass-testnet scripts/postgresql-setup.sh --createdb
PGPASSFILE=config/pgpass-testnet ./cardano-db-sync-extended-exe \
    --config config/testnet-config.yaml \
    --socket-path ../cardano-node/state-node-testnet/node.socket \
    --state-dir ledger-state/testnet \
    --schema-dir schema/

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
