### ISSUE TITLE
Update ma_tx_out or tx_in table columns for tx_out_id 

### ISSUE THREAD

**Issue by failfectionist** [IntersectMBO/cardano-db-sync#597]
**External**

**Existing Database Tables**

**Summary**
The use of 'tx_out_id' in the ma_tx_out and the tx_in tables aren't consistent. For tx_in the tx_out_id refers to the actual transaction table id. Whereas for ma_tx_out tx_out_id refers to the tx_out table id. 

Not really a high priority, but an inconsistency that could cause some really bad but "working" results if people aren't paying attention. 

Maybe we could change the tx_in tables to say tx_id_in and tx_id_out? 

**Steps to reproduce**
View tables

**System info:**
OS: Debian Buster
DB Sync Version 9.0
Node version 1.26.1

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
