### ISSUE TITLE
Export transaction_witness_set

### ISSUE THREAD

**Issue by wutzebaer** [IntersectMBO/cardano-db-sync#608]
The cardano-db-sync should export the `transaction_witness_set` of transactions, as mentioned in https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl so one can obtain the policy-script directly from the chain.

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!

**Comment by wutzebaer** [comment]
yes i think it has already been implemented in the script-table

**Comment by Cmdv** [comment]
@wutzebaer thanks for the response, new to the project so not 100% on historical things. Trying to have a spring clean 😅
