### ISSUE TITLE
Avoid Address serialisation roundtrip

### ISSUE THREAD

**Issue by kderme** [IntersectMBO/cardano-db-sync#663]
Addresses of TxOut in blocks are in a `CompactAddress` form. We deserialise this format and store it in `Generic.txOutAddress`. Later we serialise it again 2 times before storing it to the db. We can probably avoid these roundtrips.

**Comment by erikd** [comment]
When we serialize it again its not as a `CompactAddress` but as a regular `Address` right?

**Comment by erikd** [comment]
Maybe we could expand the `Generic.Tx` struct to contain both the Bech32 encoded version and the far ByteString.

**Comment by kderme** [comment]
> When we serialize it again its not as a CompactAddress but as a regular Address right?

Yes, we serialise the `Address`, however  `CompactAddress` is just a serialized address in the form of a `ShortByteString` https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/CompactAddr.hs#L46

> Maybe we could expand the Generic.Tx struct to contain both the Bech32 encoded version and the far ByteString.

I think the node doesn't use Bech32/Base58 anywhere, we will have to do this rendering for all addresses (which is quite expensive). However a serialised address is one step closer to this format than an `Address`

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
