### ISSUE TITLE
Resolve TxInputs using ledger state

### ISSUE THREAD

**Issue by kderme** [IntersectMBO/cardano-db-sync#707]
According to profiling resolving TxInputs takes a considerable amount of time of syncing. It is done for 2 main reasons:

- computing the input sum, in order to compute deposits
- find necessary fields to populate the TxIn table

most of these inputs will already be present in the ledger state. The only ones missing are UTxO created from previous transactions in the latest block, since we only get the UTxO after block application and not fine grained after Tx application. So we could get the from the ledger state, instead of doing queries to the db. If they are not found in the ledger state, we can query the db.

To get max benefits from this, we also need to change the schema of the Tx table and use real primary key, the hash of the Tx instead of autoincremental Ints. Doing one of the two, probably won't give many benefits.

**Comment by erikd** [comment]
This is not something that should be implemented in `db-sync` . The ledger should supply this via an API.

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
