### ISSUE TITLE
Enhance cardano-db-tool validate to run as a daemon with syslog broadcast

### ISSUE THREAD

**Issue by rhyslbw** [IntersectMBO/cardano-db-sync#75]
As a user of either `cardano-db-sync` or `cardano-db-sync-extended`, I wish to run the [cardano-db-tool](https://github.com/input-output-hk/cardano-db-sync/blob/b2bb096cad4be47dc60ef6ad46fcee0d09f0034b/cardano-db/app/cardano-db-tool.hs) `validate` command with arguments to specify the poll interval and credentials to remotely send results as a [syslog](https://tools.ietf.org/html/rfc5424) over TCP, so that the service health can be monitored remotely. This protocol and transport makes the service compatible with standard tooling, including [Graylog](https://www.graylog.org/), which is used by IOHK for log aggregation

A service could then be defined in nix and the nix-based Docker definition, providing feature parity across the platforms

**Comment by erikd** [comment]
Currently I am running this in a script:
```
#!/bin/bash -e

while true ; do
  date
  PGPASSFILE=config/pgpass ./cardano-db-tool validate
  sleep 30m
  echo
done
```

**Comment by disassembler** [comment]
@erikd so are we planning on making this a daemon? Are there any performance issues with having this running constantly? Are we expecting this to be included in the deployment to the explorer server?

**Comment by erikd** [comment]
This thing hits the DB pretty hard. It takes about 4 minutes to run once, and I actually think is overkill for most situations. The validations a most useful for devs working on this thing.

**Comment by rhyslbw** [comment]
For production instances, running against a slave on a separate host gains the benefit without any perf impact.

**Comment by mmahut** [comment]
Any updates on this, please?

**Comment by erikd** [comment]
No update on this. There is so much other stuff that is higher priority.

It also depends on this being fixed first: https://github.com/input-output-hk/cardano-db-sync/issues/150

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
