### ISSUE TITLE
Querying unspent tokens 

### ISSUE THREAD

**Issue by psturm51** [IntersectMBO/cardano-db-sync#819]
Hey guys! I'd love to know how one would go about finding all unspent tokens of a given policy / name and which address it resides in. Anyone have any pointers?

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
