### ISSUE TITLE
Feature request: Add SocketPath to configuration file, allowing --socket-path CLI arg to override

### ISSUE THREAD

**Issue by rdlrt** [IntersectMBO/cardano-db-sync#85]
Since cardano-node and CLI [started ](https://github.com/input-output-hk/cardano-node/pull/612) accepting `GenesisFile` and `SocketPath` , it would be good to eliminate these from cardano-db-sync as well for consistency.

**Comment by rhyslbw** [comment]
`--socket-path` is still a valid command line argument, it's not also just possible to provide in the config file

**Comment by erikd** [comment]
`genesis-file` is being moved to the config file in https://github.com/input-output-hk/cardano-db-sync/pull/188 .

**Comment by rdlrt** [comment]
Closing as stale
