### ISSUE TITLE
Extracting onchain metadata info of native tokens from cardano db sync

### ISSUE THREAD

**Issue by neverMindMap** [IntersectMBO/cardano-db-sync#897]
Its not a bug. I am trying to get all the native tokens and NFTs with their metadata information using cardano dbsync. I found the assets name and policyID from ma_tx_mint and ma_tx_out joining with utxo_view but cannot find the metadata informations of those assets like the characteristics of the assets and url etc. Could someone help me?

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
