### ISSUE TITLE
Deleting blocks up to slot and frozen

### ISSUE THREAD

**Issue by danbigthink** [IntersectMBO/cardano-db-sync#908]
Hi,

I'm not sure if this is a bug or not, but I definitely experience upgrading from versions differently in my test and lab environments running on testnet than I do to my production environments using mainnet.

After double checking that the environment is in fact working correctly, ie. block write notifications are happening, then I begin the upgrade process.

I believe my system is fairly simple, single relay node running 1.29.0, db-sync 11, and wallet server.
Upgrading my canary mainnet system has been a pain, I take the configuration files from 
https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1/ for config, byron, shelley, topology, alonzo and db-sync-config. 

After stopping the wallet server, db-sync and node, I copy over those config files, alter my docker image versions and light em up again, in k8s this is simple and the way I do all systems. I am using the versions specified in the compatibility matrix and my docker image was FROM inputoutput/cardano-db-sync:11.0.0 and is now FROM inputoutput/cardano-db-sync:11.0.4

After getting the cardano relay node running successfully and ensuring it's detecting changes, I start to watch the logs for the other 2 systems. The db-sync app just does this:
```
[db-sync-node:Info:70] [2021-10-22 21:10:39.12 UTC] Cardano.Db tip is at slot 43365556, block 6404852
[db-sync-node:Info:75] [2021-10-22 21:10:39.12 UTC] Running DB thread
[db-sync-node:Info:75] [2021-10-22 21:10:39.14 UTC] Rolling back to slot 42940763, hash cd155f53de7d3985194c73540daf2e1dc79d5f2bcd09e9c6c5830c093fb34ba8
[db-sync-node:Info:75] [2021-10-22 21:10:39.22 UTC] Deleting 20815 blocks up to slot 43365556
```
It's been doing this for a long long time now, it doesn't show progress or anything, I mean it's not terribly difficult to delete records in postgres and move on, this appears to be stuck trying to delete records. The db is fine and the db-sync app has a bunch of successes at the top of its logs.
Any ideas why this would be happening and why it didn't happen when I upgraded two separate testnet k8s clusters?

I'm afraid to do this to my non-canary production system. Currently I run this canary setup cause I've experienced similar need to resync issues with other upgrades and didn't report them before.
Thanks!

**Comment by AndresJakobs** [comment]
Cardano Mainnet.

Deleting 7997 blocks up to slot 41175126 in approx. 15 min.

8 vCPU (Intel Xeon® Gold), 32 GB RAM, 240 GB NVMe SSD.

Ubuntu 20.04.1, PostgreSQL 12, Cardano Node 1.30.0, Cardano DB-Sync Extended 11.0.4.

Unfortunately PostgreSQL only used 1 of the 8 vCPU! Increased the shared buffer to 256MB. It runs a little shorter with 1GB, but consumes much more RAM.


Oct 30 10:44:39 <myHost> cdbs[1517]: #033[34m[db-sync-node:Info:49]#033[0m [2021-10-30 08:44:39.60 UTC] Cardano.Db tip is at slot 41175126, block 6297996
Oct 30 10:44:39 <myHost> cdbs[1517]: #033[34m[db-sync-node:Info:54]#033[0m [2021-10-30 08:44:39.60 UTC] Running DB thread
Oct 30 10:44:39 <myHost> cdbs[1517]: #033[34m[db-sync-node:Info:54]#033[0m [2021-10-30 08:44:39.61 UTC] Rolling back to slot 41015240, hash 6144ad1396db1b3cbf1be2d44e3897ae6bc0e95be75ef3a62ec56cb3188cae4a
Oct 30 10:44:39 <myHost> cdbs[1517]: #033[34m[db-sync-node:Info:54]#033[0m [2021-10-30 08:44:39.77 UTC] Deleting 7997 blocks up to slot 41175126
Oct 30 10:59:26 <myHost> cdbs[1517]: #033[34m[db-sync-node:Info:54]#033[0m [2021-10-30 08:59:26.32 UTC] Blocks deleted
Oct 30 10:59:26 <myHost> cdbs[1517]: #033[34m[db-sync-node:Info:54]#033[0m [2021-10-30 08:59:26.34 UTC] Removing newer files ["/home/cnode2/db-sync/state/41212785-75f06c4e4f-292.lstate"]
Oct 30 11:00:05 <myHost> cdbs[1517]: #033[34m[db-sync-node:Info:54]#033[0m [2021-10-30 09:00:05.50 UTC] Found snapshot file for slot 41015240, hash 6144ad1396db1b3cbf1be2d44e3897ae6bc0e95be75ef3a62ec56cb3188cae4a

**Comment by AndresJakobs** [comment]
Cardano Mainnet.

Synchronization from epoch 293 to 299 in approx. 20 hours.

8 vCPU (Intel Xeon® Gold), 32 GB RAM, 240 GB NVMe SSD.

Ubuntu 20.04.1, PostgreSQL 12, Cardano Node 1.30.0, Cardano DB-Sync Extended 11.0.4.

Max. CPU usage by PostgreSQL 12 -> 0.5 vCPU
Max. Cardano DB-Sync Extended -> 1.0 vCPU
Load average: 1.10

65% CPU time through Cardano DB-Sync Extended, the rest PostgreSQL.

There is potential for optimization. At 80% system load, we could have been done within 2 hours.

**Comment by AndresJakobs** [comment]
Another addendum. Apparently the problem only occurs during batch synchronization.

In normal operation, the CPU load during synchronization is balanced with peaks of up to 60% total load, evenly distributed between Cardano DB-Sync Extended and PostgreSQL.

**Comment by kderme** [comment]
This seems related to the older and slower rollback mechanism
