### ISSUE TITLE
Can epoch_param table for epoch N be inserted before the start of epoch N?

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-db-sync#970]
Currently this table is updated at the start of the new epoch. How much earlier can these parameters be inserted?

**Comment by dmitrystas** [comment]
I'm not sure about all the parameters, but for next epoch's Nonce we have to wait until at least 70% of the current epoch has passed

**Comment by mmahut** [comment]
Can we make this happen? It would be useful for some community use cases, such as calculating the leader schedule in advance, if they have the none for the next epoch (this can be done within the stability window, so 1.5 days before the next epoch).

**Comment by Cmdv** [comment]
It looks like there hasn't been any activity on this issue for a some time. We're closing it for now. If you're still experiencing this problem or have any updates, please reopen or create a new issue. Your feedback is valuable, thank you!
