### ISSUE TITLE
Add release notes with Hardware Requirements similar to how cardano-node does it

### ISSUE THREAD

**Issue by danbigthink** [IntersectMBO/cardano-db-sync#985]
It would be nice to understand what the hardware requirements are to run this. Without this information we're all guessing (well at least I am).

I've been running dbsync/dbsync-postgres in production since June and have a decent idea of the requirements but feel like the team should document these better.

Thanks

**Comment by erikd** [comment]
Are the [system requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements) in the Readme not sufficient?

**Comment by danbigthink** [comment]
> Are the [system requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements) in the Readme not sufficient?

thanks, apparently I didn't even see them.

**Comment by erikd** [comment]
> Are these always the same between releases though? I've noticed the cardano-node project does this on releases as the requirements change from version to version.

They change as needed.

**Comment by danbigthink** [comment]
> > Are these always the same between releases though? I've noticed the cardano-node project does this on releases as the requirements change from version to version.
> 
> They change as needed.

They change in one place, overwriting what the original values were, somewhat obscuring the hardware requirement change trend.
I'd like to see some documentation consistency between Cardano projects that are commonly used by the public and  surprised you don't see it that way.

**Comment by erikd** [comment]
I have more than enough work as it is simply keeping this project running and its nowhere near as good as I think it is.

What you want would take a significant amount of my time away from actually working on `db-sync` and is almost certainly require further coordination time down the line. Unfortunately that is time I do not have, ie solving this problem is far down the priority list.

**Comment by danbigthink** [comment]
> I have more than enough work as it is simply keeping this project running and its nowhere near as good as I think it is.
> 
> What you want would take a significant amount of my time away from actually working on `db-sync` and is almost certainly require further coordination time down the line. Unfortunately that is time I do not have, ie solving this problem is far down the priority list.

I totally understand, I too am swamped and over-allocated.
I'm not trying to be difficult, I'm simply looking for documentation consistency which seems to be a struggle when it comes to anything related to Cardano. I did not mean to take this frustration out on you, I simply have higher expectations of all Cardano related projects as a whole. 

I didn't think this would be your obligation and would have expected there to be others to manage performance testing, documentation and such.
